"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
const API="https://wopt-prayer-push.wopt-windsor.workers.dev";const TOKEN_KEY="wopt:admin-token:v1";
type Contact={public_id:string;name?:string;email:string;subject:string;message:string;locale:string;platform?:string;app_version?:string;source?:string;status:string;email_status?:string;email_error?:string;created_at:string};
async function api<T>(path:string,token:string){const r=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${token}`}});const p=await r.json().catch(()=>({})) as T&{error?:string};if(!r.ok)throw new Error(p.error||`Request failed (${r.status})`);return p}
export default function SupportInbox(){
 const[token,setToken]=useState("");const[contacts,setContacts]=useState<Contact[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[error,setError]=useState("");const[selected,setSelected]=useState<Contact|null>(null);
 const load=useCallback(async(t:string)=>{const p=new URLSearchParams({limit:"200"});if(search)p.set("q",search);if(status)p.set("status",status);const d=await api<{contacts:Contact[]}>(`/admin/support/contacts?${p}`,t);setContacts(d.contacts||[])},[search,status]);
 useEffect(()=>{const t=localStorage.getItem(TOKEN_KEY)||"";setToken(t);if(t)void load(t).catch(e=>setError(e instanceof Error?e.message:"Unable to load support inbox"))},[load]);
 const filtered=useMemo(()=>contacts,[contacts]);
 if(!token)return <main style={s.center}><div style={s.card}><h1>Support Inbox</h1><p>Sign in to the Owner Control Center first.</p><a href="/admin/">Open Admin</a></div></main>;
 return <main style={s.page}><header style={s.header}><div><small style={s.eyebrow}>HASSOUN ADMIN CRM</small><h1 style={{margin:0}}>Contact Us / Support</h1></div><a href="/admin/" style={s.button}>← Main CRM</a></header>
 <section style={s.toolbar}><input style={s.input} placeholder="Search name, email, subject or message" value={search} onChange={e=>setSearch(e.target.value)}/><select style={s.input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="new">New</option><option value="open">Open</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><button style={s.primary} onClick={()=>void load(token)}>Refresh</button></section>
 {error?<div style={s.error}>{error}</div>:null}<section style={s.grid}><div style={s.card}><h2>Messages ({filtered.length})</h2>{filtered.map(c=><button key={c.public_id} style={s.ticket} onClick={()=>setSelected(c)}><div><strong>{c.subject}</strong><small>{c.name||"Unknown"} · {c.email}</small><small>{new Date(c.created_at).toLocaleString()} · {c.platform||"web"}</small></div><span>{c.status}</span></button>)}{!filtered.length?<p>No support messages found.</p>:null}</div>
 <div style={s.card}>{selected?<><div style={s.row}><h2 style={{margin:0}}>{selected.subject}</h2><span>{selected.status}</span></div><p><strong>From:</strong> {selected.name||"Unknown"} &lt;{selected.email}&gt;</p><p><strong>Platform:</strong> {selected.platform||"—"} {selected.app_version?`· v${selected.app_version}`:""}</p><p><strong>Source:</strong> {selected.source||"Contact Us"}</p><div style={s.message}>{selected.message}</div><p><strong>Email delivery:</strong> {selected.email_status||"—"}</p>{selected.email_error?<p style={s.error}>{selected.email_error}</p>:null}<a style={s.primaryLink} href={`mailto:${encodeURIComponent(selected.email)}?subject=${encodeURIComponent(`Re: ${selected.subject}`)}`}>Reply by email</a></>:<p>Select a message to view full details.</p>}</div></section></main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f6f2e8",color:"#173f35",fontFamily:"Arial,sans-serif",paddingBottom:40},center:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f6f2e8"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:"18px clamp(18px,4vw,48px)",background:"white",borderBottom:"1px solid #ded6c6"},eyebrow:{fontSize:10,fontWeight:900,letterSpacing:".14em",color:"#0b8065"},toolbar:{width:"min(1180px,calc(100% - 28px))",margin:"20px auto 12px",display:"grid",gridTemplateColumns:"1fr 180px auto",gap:8},input:{padding:"11px 12px",border:"1px solid #cdd9d5",borderRadius:10,background:"white"},button:{padding:"10px 13px",border:"1px solid #cdd9d5",borderRadius:10,textDecoration:"none",color:"#0b5b47",fontWeight:800},primary:{border:0,borderRadius:10,background:"#0b735b",color:"white",fontWeight:800,padding:"10px 14px"},grid:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto",display:"grid",gridTemplateColumns:"minmax(360px,.9fr) minmax(420px,1.1fr)",gap:14},card:{background:"white",border:"1px solid #ded6c6",borderRadius:18,padding:18},ticket:{width:"100%",display:"flex",justifyContent:"space-between",gap:12,textAlign:"left",background:"white",border:0,borderBottom:"1px solid #eee8dd",padding:"12px 2px",color:"inherit"},row:{display:"flex",justifyContent:"space-between",gap:12},message:{whiteSpace:"pre-wrap",lineHeight:1.6,background:"#faf8f2",borderRadius:12,padding:16,margin:"16px 0"},primaryLink:{display:"inline-block",background:"#0b735b",color:"white",padding:"10px 14px",borderRadius:10,textDecoration:"none",fontWeight:800},error:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto 12px",background:"#fdecec",padding:12,borderRadius:10}}
