"use client";

import { useEffect } from "react";
import { CANADA_PROVINCES, geocodeCanadaLocation, searchMosques } from "./mosqueSearch";

const STORAGE="hassoun:web-masjid-tv:v2";
const API="https://wopt-prayer-push.wopt-windsor.workers.dev";
const LIST_KEY="hassoun:paired-displays:v2";
const WIA="https://raw.githubusercontent.com/Hassoun911/WOPT/main/windsor_islamic_association_2026_prayer_times.json";
const PRAYERS=["fajr","dhuhr","asr","maghrib","isha"] as const;
type Device={id:string;code:string;name:string;token:string;pairedAt:string};
type Remote={name:string;settings:Record<string,any>;revision?:number};
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function devices():Device[]{try{return JSON.parse(localStorage.getItem(LIST_KEY)||"[]")}catch{return[]}}
function activeDevice(){const list=devices(),saved=sessionStorage.getItem("hassoun:studio-active-display-code");return list.find(x=>x.code===saved)||list[0]||null}
async function loadRemote(d:Device){const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(d.id)}`,{headers:{Authorization:`Bearer ${d.token}`},cache:"no-store"});if(!r.ok)throw new Error("Could not load display");return await r.json() as Remote}
async function saveRemote(d:Device,remote:Remote,patch:Record<string,any>){const settings={...remote.settings,...patch};const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(d.id)}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${d.token}`},body:JSON.stringify({name:remote.name,settings})});if(!r.ok)throw new Error("Could not save prayer source");return {...remote,settings}}
function readLocal(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}") as Record<string,any>}catch{return {}}}
function writeLocal(settings:Record<string,any>){localStorage.setItem(STORAGE,JSON.stringify(settings));window.dispatchEvent(new StorageEvent("storage",{key:STORAGE,newValue:JSON.stringify(settings)}))}
function complete(row:any){return PRAYERS.every(p=>String(row?.adhan?.[p]||"").trim())}
function normalizeAladhan(t:any){return {fajr:t.Fajr||"",dhuhr:t.Dhuhr||"",asr:t.Asr||"",maghrib:t.Maghrib||"",isha:t.Isha||""}}
async function resolveToday(settings:Record<string,any>){
  const today=dateKey();if(settings.prayerSourceMode==="manual"||complete(settings.prayerSchedule?.[today]))return settings;
  let adhan:Record<string,string>|null=null,source="",working={...settings};
  const city=String(working.prayerCity||working.mosqueLocation||"").toLowerCase(),mosque=String(working.selectedMosqueName||working.mosqueName||"").toLowerCase();
  const windsor=city.includes("windsor")||mosque.includes("al hijra")||mosque.includes("windsor islamic");
  try{
    if(windsor){const r=await fetch(WIA,{cache:"no-store"});if(r.ok){const j=await r.json();adhan=j.prayer_times?.[today]||null;if(adhan)source="Official Windsor Islamic Association timetable"}}
    let lat=String(working.prayerLatitude||""),lon=String(working.prayerLongitude||"");
    if(!adhan&&(!lat||!lon)&&(working.prayerPostalCode||working.prayerCity||working.prayerProvince)){
      const geo=await geocodeCanadaLocation({city:working.prayerCity,province:working.prayerProvince,postalCode:working.prayerPostalCode,country:working.prayerCountry||"Canada"});
      if(geo){lat=geo.lat;lon=geo.lon;working={...working,prayerLatitude:lat,prayerLongitude:lon,prayerCity:working.prayerCity||geo.city,prayerProvince:working.prayerProvince||geo.province,prayerPostalCode:working.prayerPostalCode||geo.postalCode}}
    }
    if(!adhan&&lat&&lon){const ts=Math.floor(Date.now()/1000),method=Number(working.calculationMethod||2);const r=await fetch(`https://api.aladhan.com/v1/timings/${ts}?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&method=${method}`,{cache:"no-store"});if(r.ok){const j=await r.json();adhan=normalizeAladhan(j?.data?.timings||{});source=working.prayerPostalCode?"Calculated from Canadian postal code / location":"Calculated from selected mosque / location"}}
    if(!adhan&&working.prayerCity){const method=Number(working.calculationMethod||2),cityQuery=[working.prayerCity,working.prayerProvince].filter(Boolean).join(", ");const r=await fetch(`https://api.aladhan.com/v1/timingsByCity?city=${encodeURIComponent(cityQuery)}&country=${encodeURIComponent(working.prayerCountry||"Canada")}&method=${method}`,{cache:"no-store"});if(r.ok){const j=await r.json();adhan=normalizeAladhan(j?.data?.timings||{});source="Calculated by city / province (AlAdhan)"}}
  }catch{}
  if(!adhan||!PRAYERS.every(p=>String(adhan?.[p]||"").trim()))return working;
  const prayerSchedule={...(working.prayerSchedule||{})};prayerSchedule[today]={...(prayerSchedule[today]||{}),adhan:{...adhan,...(prayerSchedule[today]?.adhan||{})}};
  const loc=[working.prayerCity,working.prayerProvince,working.prayerPostalCode].filter(Boolean).join(", ");return {...working,prayerSchedule,prayerSourceResolved:source,mosqueLocation:working.mosqueLocation||loc};
}

export default function PrayerSourceResolverEnhancer(){
  useEffect(()=>{
    let stopped=false;const tv=async()=>{if(stopped||location.pathname.includes('/masjid-tv/devices'))return;const s=readLocal(),n=await resolveToday(s);if(JSON.stringify(n)!==JSON.stringify(s))writeLocal(n)};void tv();const tvTimer=window.setInterval(()=>void tv(),60000);
    const admin=async()=>{
      if(stopped||!location.pathname.includes('/masjid-tv/devices'))return;const device=activeDevice();if(!device)return;const h=Array.from(document.querySelectorAll('h2')).find(x=>(x.textContent||'').includes('Live display editor'));const section=h?.closest('section');if(!section||section.querySelector('[data-prayer-source-resolver="1"]'))return;
      let remote:Remote;try{remote=await loadRemote(device)}catch{return}
      const provinceOptions=CANADA_PROVINCES.map(p=>`<option value="${p}">${p}</option>`).join("");const field='width:100%;padding:10px;border-radius:9px;background:#082b26;color:#fff;border:1px solid #56776e';
      const box=document.createElement('details');box.dataset.prayerSourceResolver='1';box.open=true;box.style.cssText='margin:12px 0;padding:14px;border:1px solid #806f3e;border-radius:14px;background:#082f2a;color:white';
      box.innerHTML=`<summary style="cursor:pointer;color:#efc56a;font-size:18px;font-weight:900">Prayer location & source</summary><div style="display:grid;gap:10px;margin-top:12px"><label>Source mode<select data-mode style="${field}"><option value="auto">Automatic — best source</option><option value="official">Prefer official mosque timetable</option><option value="calculated">Calculated by location</option><option value="manual">Manual only</option></select></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><label>City<input data-city style="${field}" placeholder="Windsor"></label><label>Province<select data-province style="${field}"><option value="">Select province</option>${provinceOptions}</select></label></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><label>Postal code<input data-postal style="${field}" placeholder="N9A 6V2"></label><label>Country<input data-country style="${field}" placeholder="Canada"></label></div><label>Search mosque<input data-search style="${field}" placeholder="Start typing mosque name…" autocomplete="off"></label><small style="color:#9fc1b6">Suggestions appear while typing and use mosque name, city, province and postal code.</small><div data-results style="display:grid;gap:7px;max-height:280px;overflow:auto"></div><button data-find style="padding:10px 14px;border-radius:999px;border:1px solid #d3af58;background:#d9b36b;color:#15342b;font-weight:900;cursor:pointer;justify-self:start">Search all nearby mosques</button><label>Calculation method<select data-method style="${field}"><option value="2">ISNA</option><option value="3">Muslim World League</option><option value="4">Umm Al-Qura</option><option value="5">Egyptian Authority</option></select></label><div data-source-status style="font-size:12px;color:#aee5bf"></div></div>`;
      section.insertBefore(box,section.firstChild?.nextSibling||null);const q=<T extends HTMLElement>(s:string)=>box.querySelector<T>(s)!;
      const mode=q<HTMLSelectElement>('[data-mode]'),city=q<HTMLInputElement>('[data-city]'),province=q<HTMLSelectElement>('[data-province]'),postal=q<HTMLInputElement>('[data-postal]'),country=q<HTMLInputElement>('[data-country]'),search=q<HTMLInputElement>('[data-search]'),method=q<HTMLSelectElement>('[data-method]'),status=q<HTMLElement>('[data-source-status]'),results=q<HTMLElement>('[data-results]');
      const hydrate=()=>{mode.value=String(remote.settings.prayerSourceMode||'auto');city.value=String(remote.settings.prayerCity||'Windsor');province.value=String(remote.settings.prayerProvince||'Ontario');postal.value=String(remote.settings.prayerPostalCode||'');country.value=String(remote.settings.prayerCountry||'Canada');search.value=String(remote.settings.selectedMosqueName||remote.settings.mosqueSearchText||'');method.value=String(remote.settings.calculationMethod||2);status.textContent=remote.settings.prayerSourceResolved?`Current source: ${remote.settings.prayerSourceResolved}`:'Automatic source resolver ready'};hydrate();
      const persist=async(patch:Record<string,any>)=>{try{status.textContent='Saving…';const merged={...remote.settings,...patch};const loc=[merged.prayerCity,merged.prayerProvince,merged.prayerPostalCode].filter(Boolean).join(', ');remote=await saveRemote(device,remote,{...patch,mosqueLocation:loc||merged.mosqueLocation});status.textContent='Saved · display will refresh automatically'}catch(e){status.textContent=e instanceof Error?e.message:'Save failed'}};
      mode.onchange=()=>void persist({prayerSourceMode:mode.value});city.onchange=()=>void persist({prayerCity:city.value});province.onchange=()=>void persist({prayerProvince:province.value});postal.onchange=()=>void persist({prayerPostalCode:postal.value.toUpperCase()});country.onchange=()=>void persist({prayerCountry:country.value});method.onchange=()=>void persist({calculationMethod:Number(method.value)});
      let searchTimer:number|undefined,seq=0;const runSearch=async()=>{const term=search.value.trim();if(!term&&!city.value&&!postal.value){results.textContent='Enter a mosque name, city or postal code.';return}const current=++seq;results.innerHTML='<span style="color:#9fc1b6">Searching mosque directory…</span>';try{const rows=await searchMosques({text:term,city:city.value,province:province.value,postalCode:postal.value,country:country.value||'Canada'});if(current!==seq)return;results.innerHTML='';if(!rows.length){results.textContent='No matches yet. Try part of the mosque name, nearby city, province, or postal code.';return}rows.forEach(row=>{const b=document.createElement('button');b.type='button';b.style.cssText='text-align:left;padding:10px;border-radius:10px;border:1px solid #44675d;background:#0a3b34;color:#fff;cursor:pointer';b.innerHTML=`<strong>${row.name}</strong><br><small>${row.displayName}</small>`;b.onclick=()=>{search.value=row.name;city.value=row.city||city.value;province.value=row.province||province.value;postal.value=row.postalCode||postal.value;void persist({selectedMosqueName:row.name,mosqueName:row.name,mosqueSearchText:row.name,prayerCity:city.value,prayerProvince:province.value,prayerPostalCode:postal.value,prayerCountry:row.country||country.value||'Canada',prayerLatitude:row.lat,prayerLongitude:row.lon,prayerSourceMode:'auto'});results.innerHTML='<span style="color:#aee5bf">Mosque selected. Prayer source will resolve automatically.</span>'};results.appendChild(b)})}catch{if(current===seq)results.textContent='Mosque search is temporarily unavailable. City/postal-code prayer times still work.'}};
      search.oninput=()=>{if(searchTimer)clearTimeout(searchTimer);if(search.value.trim().length<2){results.innerHTML='';return}searchTimer=window.setTimeout(()=>void runSearch(),450)};q<HTMLButtonElement>('[data-find]').onclick=()=>void runSearch();
    };
    void admin();const adminTimer=window.setInterval(()=>void admin(),1000);return()=>{stopped=true;window.clearInterval(tvTimer);window.clearInterval(adminTimer);document.querySelector('[data-prayer-source-resolver]')?.remove()}
  },[]);return null;
}
