"use client";

import { useEffect, useState } from "react";

const API = "https://wopt-prayer-push.wopt-windsor.workers.dev";

type AboutConfig = {
  sadaqahTitleEn:string; sadaqahTitleAr:string; sadaqahBodyEn:string; sadaqahBodyAr:string;
  names:string[]; donationEnabled:boolean; donationUrl:string;
  donationTitleEn:string; donationTitleAr:string; donationBodyEn:string; donationBodyAr:string;
};
type GuideConfig = { enabled:boolean; titleEn:string; titleAr:string; introEn:string; introAr:string };
const DEFAULT_ABOUT:AboutConfig={sadaqahTitleEn:"A continuing Sadaqah Jariyah",sadaqahTitleAr:"صدقة جارية مستمرة",sadaqahBodyEn:"Hassoun is built as a continuing charity dedicated to spreading beneficial Islamic knowledge, helping people protect their prayers, read Qur’an, learn and teach their families.",sadaqahBodyAr:"بُني Hassoun كصدقة جارية لنشر العلم الإسلامي النافع ومساعدة الناس على المحافظة على الصلاة وقراءة القرآن والتعلم وتعليم أسرهم.",names:["Abdul Jalil Hassoun","Salwa Hassoun"],donationEnabled:false,donationUrl:"",donationTitleEn:"Contribute to this Sadaqah Jariyah",donationTitleAr:"ساهم في هذه الصدقة الجارية",donationBodyEn:"Your contribution can help support hosting, development, Qur’an tools, prayer services and future educational features so the benefit can continue for more people.",donationBodyAr:"يمكن لمساهمتك أن تساعد في دعم الاستضافة والتطوير وأدوات القرآن وخدمات الصلاة والميزات التعليمية القادمة ليستمر النفع لعدد أكبر من الناس."};
const DEFAULT_GUIDE:GuideConfig={enabled:true,titleEn:"Learn the App",titleAr:"تعرّف على التطبيق",introEn:"Search any Hassoun feature and learn how it works with easy steps, examples and tips.",introAr:"ابحث عن أي ميزة في Hassoun وتعلم طريقة استخدامها بخطوات وأمثلة ونصائح سهلة."};

async function api(path:string, token:string, init:RequestInit={}) {
 const headers=new Headers(init.headers); headers.set("Authorization",`Bearer ${token}`); if(init.body) headers.set("Content-Type","application/json");
 const r=await fetch(`${API}${path}`,{...init,headers}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||`Request failed (${r.status})`); return data;
}

export default function AboutGuideControl({token}:{token:string}) {
 const [about,setAbout]=useState<AboutConfig>(DEFAULT_ABOUT); const [guide,setGuide]=useState<GuideConfig>(DEFAULT_GUIDE); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{void api("/admin/settings",token).then((data:any)=>{for(const row of data.settings||[]){if(row.key==="about_sadaqah"&&row.value) setAbout({...DEFAULT_ABOUT,...row.value}); if(row.key==="feature_guide"&&row.value) setGuide({...DEFAULT_GUIDE,...row.value});}}).catch(e=>setError(e.message));},[token]);
 const save=async()=>{setBusy(true);setError("");setNotice("");try{await api("/admin/settings/about_sadaqah",token,{method:"POST",body:JSON.stringify({value:about})});await api("/admin/settings/feature_guide",token,{method:"POST",body:JSON.stringify({value:guide})});setNotice("About, Sadaqah, donation and feature-guide settings saved.");}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false)}};
 const namesText=about.names.join("\n");
 return <section>
  <div style={s.titleRow}><div><p style={s.eyebrow}>APP CONTENT CONTROL</p><h1 style={s.title}>About, Sadaqah & Feature Guide</h1><p style={s.muted}>Control the memorial dedication, verified donation link and in-app learning guide without rebuilding the app.</p></div><button style={s.primary} disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save all changes"}</button></div>
  {error?<div style={s.error}>{error}</div>:null}{notice?<div style={s.success}>{notice}</div>:null}
  <div style={s.grid}>
   <div style={s.panel}><h2 style={s.panelTitle}>🤲 Sadaqah Jariyah dedication</h2><Label text="English heading"/><input style={s.input} value={about.sadaqahTitleEn} onChange={e=>setAbout({...about,sadaqahTitleEn:e.target.value})}/><Label text="Arabic heading"/><input style={s.input} dir="rtl" value={about.sadaqahTitleAr} onChange={e=>setAbout({...about,sadaqahTitleAr:e.target.value})}/><Label text="English message"/><textarea style={s.textarea} value={about.sadaqahBodyEn} onChange={e=>setAbout({...about,sadaqahBodyEn:e.target.value})}/><Label text="Arabic message"/><textarea style={s.textarea} dir="rtl" value={about.sadaqahBodyAr} onChange={e=>setAbout({...about,sadaqahBodyAr:e.target.value})}/><Label text="Dedicated names — one per line"/><textarea style={s.textarea} value={namesText} onChange={e=>setAbout({...about,names:e.target.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)})}/><div style={s.preview}><strong>Current dedication</strong>{about.names.map(n=><div key={n}>• {n}</div>)}</div></div>
   <div style={s.panel}><h2 style={s.panelTitle}>💚 Donation section</h2><div style={s.toggleRow}><div><strong>Enable Donate button</strong><div style={s.muted}>Leave OFF until the destination URL is verified.</div></div><input type="checkbox" checked={about.donationEnabled} onChange={e=>setAbout({...about,donationEnabled:e.target.checked})}/></div><Label text="Verified HTTPS donation URL"/><input style={s.input} placeholder="https://..." value={about.donationUrl} onChange={e=>setAbout({...about,donationUrl:e.target.value})}/><Label text="English title"/><input style={s.input} value={about.donationTitleEn} onChange={e=>setAbout({...about,donationTitleEn:e.target.value})}/><Label text="Arabic title"/><input style={s.input} dir="rtl" value={about.donationTitleAr} onChange={e=>setAbout({...about,donationTitleAr:e.target.value})}/><Label text="English donation message"/><textarea style={s.textarea} value={about.donationBodyEn} onChange={e=>setAbout({...about,donationBodyEn:e.target.value})}/><Label text="Arabic donation message"/><textarea style={s.textarea} dir="rtl" value={about.donationBodyAr} onChange={e=>setAbout({...about,donationBodyAr:e.target.value})}/><div style={about.donationEnabled?s.enabled:s.disabled}>{about.donationEnabled?"Donate button enabled":"Donate button safely disabled"}</div></div>
   <div style={s.panel}><h2 style={s.panelTitle}>🧭 Learn the App</h2><div style={s.toggleRow}><div><strong>Feature guide enabled</strong><div style={s.muted}>Searchable in Settings → Learn the App.</div></div><input type="checkbox" checked={guide.enabled} onChange={e=>setGuide({...guide,enabled:e.target.checked})}/></div><Label text="English title"/><input style={s.input} value={guide.titleEn} onChange={e=>setGuide({...guide,titleEn:e.target.value})}/><Label text="Arabic title"/><input style={s.input} dir="rtl" value={guide.titleAr} onChange={e=>setGuide({...guide,titleAr:e.target.value})}/><Label text="English intro"/><textarea style={s.textarea} value={guide.introEn} onChange={e=>setGuide({...guide,introEn:e.target.value})}/><Label text="Arabic intro"/><textarea style={s.textarea} dir="rtl" value={guide.introAr} onChange={e=>setGuide({...guide,introAr:e.target.value})}/><div style={s.preview}><strong>Guide coverage</strong><div>🕌 Prayer & GPS</div><div>🔔 Adhan & alarms</div><div>📖 Qur’an & Tajweed</div><div>🎓 Al-Hafiz + AI Teacher</div><div>🎙️ Recitation testing</div><div>🏆 Games & history</div><div>🗓️ Islamic events</div><div>🧩 Widgets</div><div>📣 Ticker</div><div>🛠️ Troubleshooting</div></div></div>
  </div>
 </section>;
}
function Label({text}:{text:string}){return <label style={s.label}>{text}</label>}
const s:Record<string,React.CSSProperties>={titleRow:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:16,flexWrap:"wrap",marginBottom:16},eyebrow:{fontSize:11,fontWeight:900,letterSpacing:1.2,color:"#987532",margin:0},title:{fontSize:28,color:"#153f35",margin:"4px 0 6px"},muted:{fontSize:12,color:"#71807b"},primary:{border:0,borderRadius:12,background:"#0b654f",color:"white",padding:"11px 16px",fontWeight:800,cursor:"pointer"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:14},panel:{background:"white",border:"1px solid #e1ddd4",borderRadius:18,padding:16,minWidth:0},panelTitle:{fontSize:18,color:"#173f35",margin:"0 0 12px"},label:{display:"block",fontSize:11,fontWeight:800,color:"#5e6e68",margin:"11px 0 5px"},input:{width:"100%",boxSizing:"border-box",border:"1px solid #dcd8cf",borderRadius:11,padding:"10px 11px",fontSize:13},textarea:{width:"100%",boxSizing:"border-box",border:"1px solid #dcd8cf",borderRadius:11,padding:"10px 11px",fontSize:13,minHeight:88,resize:"vertical"},toggleRow:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,background:"#f7f6f2",borderRadius:12,padding:11},preview:{marginTop:12,background:"#edf5f1",borderRadius:12,padding:11,fontSize:12,lineHeight:1.7,color:"#4e655d"},enabled:{marginTop:12,padding:10,borderRadius:10,background:"#e7f6ee",color:"#17633d",fontWeight:800},disabled:{marginTop:12,padding:10,borderRadius:10,background:"#f1f2f2",color:"#60706a",fontWeight:800},error:{background:"#fdecec",color:"#962929",padding:11,borderRadius:10,marginBottom:12},success:{background:"#e8f6ee",color:"#17633d",padding:11,borderRadius:10,marginBottom:12}};