"use client";

import {useEffect} from "react";

const API="https://wopt-prayer-push.wopt-windsor.workers.dev";
const LIST_KEY="hassoun:paired-displays:v2";
type Device={id:string;code:string;name:string;token:string;pairedAt:string};

type ScheduleRow={date:string;fajr:string;fajrIqama:string;dhuhr:string;dhuhrIqama:string;asr:string;asrIqama:string;maghrib:string;maghribIqama:string;isha:string;ishaIqama:string;confidence?:number};
function devices():Device[]{try{return JSON.parse(localStorage.getItem(LIST_KEY)||"[]")}catch{return []}}
function activeDevice():Device|null{
  const cards=Array.from(document.querySelectorAll<HTMLElement>("article"));
  for(const card of cards){const manage=Array.from(card.querySelectorAll("button")).find(b=>(b.textContent||"").includes("Manage live"));if(!manage)continue;const code=(card.textContent||"").match(/\b\d{6}\b/)?.[0];if(code&&card.getAttribute("style")?.includes("239"))return devices().find(d=>d.code===code)||null;}
  const h=Array.from(document.querySelectorAll("h2,h3")).find(x=>(x.textContent||"").includes("Live display editor"));if(h){const code=document.body.textContent?.match(/\b\d{6}\b/)?.[0];if(code)return devices().find(d=>d.code===code)||null;}
  return devices()[0]||null;
}
async function load(device:Device){const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(device.id)}`,{headers:{Authorization:`Bearer ${device.token}`},cache:"no-store"});if(!r.ok)throw new Error("Could not load display");return await r.json() as {name:string;settings:Record<string,unknown>}}
async function patch(device:Device,extra:Record<string,unknown>){const current=await load(device);const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(device.id)}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${device.token}`},body:JSON.stringify({name:current.name,settings:{...current.settings,...extra}})});if(!r.ok)throw new Error("Could not update display");}
function button(label:string){const b=document.createElement("button");b.type="button";b.textContent=label;b.style.cssText="padding:10px 13px;border-radius:10px;border:1px solid #d9b36b;background:#d9b36b;color:#102c25;font-weight:900;cursor:pointer";return b}
function fileToDataUrl(file:File,max=420):Promise<string>{return new Promise((resolve,reject)=>{if(file.type==="image/svg+xml"){const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||""));fr.onerror=()=>reject(new Error("Could not read logo"));fr.readAsDataURL(file);return;}const img=new Image();const fr=new FileReader();fr.onload=()=>{img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext("2d");if(!ctx)return reject(new Error("Could not process logo"));ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/png",.92))};img.onerror=()=>reject(new Error("Unsupported image"));img.src=String(fr.result||"")};fr.onerror=()=>reject(new Error("Could not read logo"));fr.readAsDataURL(file)})}
function toBase64(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||"").split(",")[1]||"");r.onerror=()=>reject(new Error("Could not read file"));r.readAsDataURL(file)})}

export default function LocalLogoAndScheduleImport(){
 useEffect(()=>{
  let stopped=false;
  const enhance=()=>{
   if(stopped)return;
   const headings=Array.from(document.querySelectorAll<HTMLHeadingElement>("h3"));
   const identity=headings.find(h=>(h.textContent||"").includes("Mosque & display identity"));
   if(identity?.parentElement&&!identity.parentElement.querySelector("[data-local-logo-upload='1']")){
    const host=identity.parentElement;const urlLabel=Array.from(host.querySelectorAll("label")).find(l=>(l.textContent||"").includes("Logo URL"));
    const box=document.createElement("div");box.dataset.localLogoUpload="1";box.style.cssText="display:grid;gap:8px;padding:10px;border:1px solid #46675e;border-radius:12px;background:#0a332d";
    box.innerHTML='<strong style="color:#f1c86f">Upload logo from this device</strong><div style="font-size:12px;color:#9fb9b1">PNG, JPG, WEBP or SVG. The image is optimized and pushed to the paired display.</div><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" style="color:#fff"><div data-logo-status style="font-size:12px;color:#aee5bf"></div>';
    const input=box.querySelector<HTMLInputElement>("input")!;const status=box.querySelector<HTMLElement>("[data-logo-status]")!;
    input.onchange=async()=>{const f=input.files?.[0];const d=activeDevice();if(!f||!d)return;status.textContent="Processing logo…";try{if(f.size>4_000_000)throw new Error("Logo must be under 4 MB");const data=await fileToDataUrl(f);await patch(d,{logoUrl:data,showLogo:true});status.textContent="Live · logo uploaded. The TV will update within a few seconds.";const urlInput=urlLabel?.querySelector<HTMLInputElement>("input");if(urlInput){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(urlInput,data);urlInput.dispatchEvent(new Event("input",{bubbles:true}))}}catch(e){status.textContent=e instanceof Error?e.message:"Upload failed"}};
    urlLabel?.insertAdjacentElement("afterend",box);
   }
   const prayer=headings.find(h=>(h.textContent||"").includes("Prayer table & Iqama"));
   if(prayer?.parentElement&&!prayer.parentElement.querySelector("[data-bulk-prayer-import='1']")){
    const host=prayer.parentElement;const panel=document.createElement("section");panel.dataset.bulkPrayerImport="1";panel.style.cssText="display:grid;gap:10px;padding:13px;border:1px solid #826f45;border-radius:13px;background:#0b3b33;margin:4px 0 6px";
    panel.innerHTML='<strong style="color:#f1c86f;font-size:16px">Bulk Prayer Schedule Import</strong><div style="font-size:12px;color:#a8c2b9">Upload a full month or year. Hassoun AI will detect dates, all 5 prayer times and Iqama times, then show a preview before applying.</div><input data-schedule-file type="file" accept=".pdf,.json,.csv,.txt,.xlsx,.xls,.xlsm,.xlsb,.ods,.numbers,.docx,text/plain,text/csv,application/json,application/pdf" style="color:#fff"><div style="display:flex;gap:8px;flex-wrap:wrap"><button data-analyze type="button">Analyze file with Hassoun AI</button><button data-apply type="button" disabled>Apply imported schedule</button></div><div data-schedule-status style="font-size:12px;color:#d9b36b"></div><div data-schedule-preview style="max-height:280px;overflow:auto"></div>';
    panel.querySelectorAll("button").forEach(b=>{b.style.cssText="padding:9px 12px;border-radius:10px;border:1px solid #d9b36b;background:#d9b36b;color:#102c25;font-weight:900;cursor:pointer"});
    const fileInput=panel.querySelector<HTMLInputElement>("[data-schedule-file]")!;const analyze=panel.querySelector<HTMLButtonElement>("[data-analyze]")!;const apply=panel.querySelector<HTMLButtonElement>("[data-apply]")!;const status=panel.querySelector<HTMLElement>("[data-schedule-status]")!;const preview=panel.querySelector<HTMLElement>("[data-schedule-preview]")!;let rows:ScheduleRow[]=[];
    analyze.onclick=async()=>{const file=fileInput.files?.[0],d=activeDevice();if(!file||!d){status.textContent="Choose a schedule file first.";return}if(file.size>18_000_000){status.textContent="File is too large. Please keep it under 18 MB.";return}status.textContent="Reading and analyzing schedule…";analyze.disabled=true;apply.disabled=true;preview.innerHTML="";try{const base64=await toBase64(file);const r=await fetch(`${API}/masjid-displays/ai/schedule-import`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${d.token}`},body:JSON.stringify({deviceId:d.id,fileName:file.name,mimeType:file.type||"application/octet-stream",base64})});const out=await r.json() as {rows?:ScheduleRow[];error?:string;warnings?:string[]};if(!r.ok)throw new Error(out.error||"Could not analyze schedule");rows=Array.isArray(out.rows)?out.rows:[];if(!rows.length)throw new Error("No prayer dates were detected");status.textContent=`Found ${rows.length} daily schedule rows${out.warnings?.length?` · ${out.warnings.join(" · ")}`:""}`;const table=document.createElement("table");table.style.cssText="width:100%;border-collapse:collapse;font-size:11px;color:#fff";table.innerHTML='<thead><tr><th>Date</th><th>Fajr</th><th>F Iq.</th><th>Dhuhr</th><th>D Iq.</th><th>Asr</th><th>A Iq.</th><th>Maghrib</th><th>M Iq.</th><th>Isha</th><th>I Iq.</th></tr></thead><tbody></tbody>';const tbody=table.querySelector("tbody")!;rows.slice(0,80).forEach((row,i)=>{const tr=document.createElement("tr");const keys:[keyof ScheduleRow,string][]=[["date","Date"],["fajr","Fajr"],["fajrIqama","F Iq"],["dhuhr","Dhuhr"],["dhuhrIqama","D Iq"],["asr","Asr"],["asrIqama","A Iq"],["maghrib","Maghrib"],["maghribIqama","M Iq"],["isha","Isha"],["ishaIqama","I Iq"]];keys.forEach(([key])=>{const td=document.createElement("td");td.style.cssText="border-top:1px solid #385d54;padding:3px";const inp=document.createElement("input");inp.value=String(row[key]||"");inp.style.cssText="width:100%;min-width:70px;background:#082b26;color:white;border:1px solid #46675e;border-radius:5px;padding:4px";inp.onchange=()=>{(rows[i] as Record<string,unknown>)[key]=inp.value};td.appendChild(inp);tr.appendChild(td)});tbody.appendChild(tr)});preview.appendChild(table);if(rows.length>80){const more=document.createElement("div");more.textContent=`Previewing first 80 of ${rows.length} rows. All rows will be imported.`;more.style.cssText="padding:8px;color:#a8c2b9";preview.appendChild(more)}apply.disabled=false}catch(e){status.textContent=e instanceof Error?e.message:"Schedule analysis failed"}finally{analyze.disabled=false}};
    apply.onclick=async()=>{const d=activeDevice();if(!d||!rows.length)return;status.textContent="Applying full schedule to display…";apply.disabled=true;try{const schedule:Record<string,unknown>={};rows.forEach(r=>{schedule[r.date]={adhan:{fajr:r.fajr,dhuhr:r.dhuhr,asr:r.asr,maghrib:r.maghrib,isha:r.isha},iqama:{fajr:r.fajrIqama,dhuhr:r.dhuhrIqama,asr:r.asrIqama,maghrib:r.maghribIqama,isha:r.ishaIqama}}});await patch(d,{prayerSchedule:schedule,prayerMode:"custom",showIqama:true,showPrayerCards:true});status.textContent=`Live · imported ${rows.length} dates. You can still edit individual values manually.`}catch(e){status.textContent=e instanceof Error?e.message:"Could not apply schedule"}finally{apply.disabled=false}};
    host.insertBefore(panel,prayer.nextSibling);
   }
  };
  enhance();const timer=window.setInterval(enhance,700);return()=>{stopped=true;window.clearInterval(timer);document.querySelectorAll("[data-local-logo-upload='1'],[data-bulk-prayer-import='1']").forEach(x=>x.remove())};
 },[]);
 return null;
}
