"use client";

import { useEffect, useRef, useState } from "react";

const API="https://wopt-prayer-push.wopt-windsor.workers.dev";
const LIST_KEY="hassoun:paired-displays:v2";
type Display={id:string;code:string;name:string;token:string;pairedAt:string};
type Remote={name:string;settings:Record<string,any>;revision:number;lastSeenAt?:string};
type Part="identity"|"clock"|"next"|"prayers"|"announcements"|"verse"|"donation"|"appearance";

const fieldStyle={width:"100%",padding:10,borderRadius:9,border:"1px solid #56776e",background:"#082b26",color:"#fff",fontSize:16} as const;
const prayers=["fajr","dhuhr","asr","maghrib","isha"] as const;
const prayerLabels:{[k:string]:string}={fajr:"Fajr",dhuhr:"Dhuhr",asr:"Asr",maghrib:"Maghrib",isha:"Isha"};
const demoTimes:{[k:string]:string}={fajr:"5:25 AM",dhuhr:"1:33 PM",asr:"5:15 PM",maghrib:"8:11 PM",isha:"9:30 PM"};

function color(v:any,fallback:string){return typeof v==="string"&&/^#[0-9a-f]{6}$/i.test(v)?v:fallback}
function announcements(settings:Record<string,any>){return Array.isArray(settings.announcements)?settings.announcements:[]}

export default function DisplaysPage(){
  const [items,setItems]=useState<Display[]>([]);
  const [editing,setEditing]=useState<string>("");
  const [remote,setRemote]=useState<Remote|null>(null);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState("");
  const [part,setPart]=useState<Part>("identity");
  const saveTimer=useRef<number|undefined>(undefined);
  const latest=useRef<Remote|null>(null);

  useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(LIST_KEY)||"[]"))}catch{}},[]);
  useEffect(()=>{latest.current=remote},[remote]);
  useEffect(()=>()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current)},[]);

  const saveList=(next:Display[])=>{setItems(next);localStorage.setItem(LIST_KEY,JSON.stringify(next))};
  const remove=(id:string)=>saveList(items.filter(x=>x.id!==id));

  const load=async(item:Display)=>{setEditing(item.id);setBusy(true);setMessage("");try{const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(item.id)}`,{headers:{Authorization:`Bearer ${item.token}`},cache:"no-store"});const d=await r.json() as Remote&{error?:string};if(!r.ok)throw new Error(d.error||"Could not load display");setRemote(d);setPart("identity")}catch(e){setRemote(null);setMessage(e instanceof Error?e.message:"Could not load display")}finally{setBusy(false)}};

  const send=async(next:Remote)=>{const item=items.find(x=>x.id===editing);if(!item)return;setMessage("Updating display…");try{const r=await fetch(`${API}/masjid-displays/control/${encodeURIComponent(item.id)}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${item.token}`},body:JSON.stringify({name:next.name,settings:next.settings})});const d=await r.json() as {ok?:boolean;revision?:number;error?:string};if(!r.ok||!d.ok)throw new Error(d.error||"Could not save settings");setRemote(cur=>cur?{...cur,revision:d.revision||cur.revision+1}:cur);saveList(items.map(x=>x.id===item.id?{...x,name:next.name}:x));setMessage("Live · updated on display")}catch(e){setMessage(e instanceof Error?e.message:"Could not update display")}};

  const queue=(next:Remote)=>{latest.current=next;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>{const v=latest.current;if(v)void send(v)},350)};
  const mutate=(fn:(r:Remote)=>Remote)=>setRemote(cur=>{if(!cur)return cur;const next=fn(cur);queue(next);return next});
  const updateSetting=(key:string,value:any)=>mutate(r=>({...r,settings:{...r.settings,[key]:value}}));
  const updateName=(name:string)=>mutate(r=>({...r,name:name.slice(0,40)}));
  const updateIqama=(key:string,value:string)=>mutate(r=>({...r,settings:{...r.settings,iqama:{...(r.settings.iqama||{}),[key]:value}}}));
  const updateAnnouncement=(index:number,key:"title"|"body",value:string)=>mutate(r=>{const list=announcements(r.settings).map((a:any,i:number)=>i===index?{...a,[key]:value}:a);return {...r,settings:{...r.settings,announcements:list}}});
  const addAnnouncement=()=>mutate(r=>({...r,settings:{...r.settings,announcements:[...announcements(r.settings),{id:`a${Date.now()}`,title:"New announcement",body:"Add details here"}]}}));
  const removeAnnouncement=(index:number)=>mutate(r=>({...r,settings:{...r.settings,announcements:announcements(r.settings).filter((_:any,i:number)=>i!==index)}}));

  const bool=(key:string,label:string)=><label style={{display:"flex",gap:9,alignItems:"center",fontWeight:800}}><input type="checkbox" checked={remote?.settings[key]!==false} onChange={e=>updateSetting(key,e.target.checked)}/>{label}</label>;
  const selectStyle=(p:Part)=>({outline:part===p?"3px solid #f0c76d":"2px solid transparent",outlineOffset:-2,cursor:"pointer",transition:"outline .15s"});

  const Preview=()=>{if(!remote)return null;const s=remote.settings;const bg=color(s.backgroundColor,"#063d34");const card=color(s.cardColor,"#0a5548");const accent=color(s.accentColor,"#e7bd59");const text=color(s.textColor,"#ffffff");const anns=announcements(s);return <div style={{background:bg,color:text,border:`2px solid ${accent}`,borderRadius:16,overflow:"hidden",aspectRatio:"16 / 9",minHeight:310,display:"grid",gridTemplateRows:"28% 14% 1fr 9%",fontFamily:"Arial,sans-serif",boxShadow:"0 14px 36px rgba(0,0,0,.26)"}}>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1.15fr 1fr",alignItems:"center",padding:"12px 16px",gap:10,background:`linear-gradient(135deg,${bg},${card})`}}>
      <button onClick={()=>setPart("identity")} style={{...selectStyle("identity"),background:"transparent",border:0,color:text,textAlign:"left",padding:6}}>{s.showLogo!==false?<div style={{fontSize:28,color:accent}}>☪</div>:null}<strong style={{display:"block",fontSize:18}}>{s.mosqueName||"Your Masjid Name"}</strong>{s.showLocation!==false?<small>{s.mosqueLocation||"Mosque location not set"}</small>:null}</button>
      <button onClick={()=>setPart("clock")} style={{...selectStyle("clock"),background:"transparent",border:0,color:text,textAlign:"center",padding:6}}>{s.showClock!==false?<strong style={{display:"block",fontSize:34}}>10:32:18 PM</strong>:<span>Clock hidden</span>}{s.showDate!==false?<small>Sunday, August 30, 2026</small>:null}</button>
      <button onClick={()=>setPart("verse")} style={{...selectStyle("verse"),background:"transparent",border:0,color:text,textAlign:"right",padding:6,fontSize:11}}>{s.showVerse!==false?(s.verseText||"Indeed, in the remembrance of Allah do hearts find rest. — Qur’an 13:28"):"Verse hidden"}</button>
    </div>
    <button onClick={()=>setPart("next")} style={{...selectStyle("next"),margin:"0 14px",border:`1px solid ${accent}`,borderRadius:12,background:card,color:text,display:"grid",gridTemplateColumns:"1fr 1fr 1fr",alignItems:"center",padding:"7px 12px"}}><span style={{textAlign:"left",fontSize:10,color:accent}}>NEXT PRAYER<br/><b style={{fontSize:18,color:text}}>Fajr</b></span><strong style={{fontSize:23}}>5:25 AM</strong><span style={{textAlign:"right",fontSize:10}}>IQAMA<br/><b style={{fontSize:17}}>{s.iqama?.fajr||"—"}</b></span></button>
    <div style={{display:"grid",gridTemplateColumns:"45% 55%",gap:10,padding:"10px 14px"}}>
      <button onClick={()=>setPart("prayers")} style={{...selectStyle("prayers"),border:`1px solid ${accent}`,borderRadius:12,background:card,color:text,padding:"8px 10px",textAlign:"left"}}><div style={{display:"grid",gridTemplateColumns:"1.3fr .8fr .7fr",fontSize:9,color:accent,paddingBottom:5}}><b>SALAH</b><b>AZAN</b><b>IQAMA</b></div>{prayers.map(p=><div key={p} style={{display:"grid",gridTemplateColumns:"1.3fr .8fr .7fr",padding:"5px 0",borderTop:"1px solid rgba(255,255,255,.12)",fontSize:11}}><b>{prayerLabels[p]}</b><span>{demoTimes[p]}</span><span>{s.iqama?.[p]||"—"}</span></div>)}</button>
      <div style={{display:"grid",gridTemplateColumns:"1.5fr .8fr",gap:8}}><button onClick={()=>setPart("announcements")} style={{...selectStyle("announcements"),border:`1px solid ${accent}`,borderRadius:12,background:card,color:text,padding:10,textAlign:"left"}}><b style={{fontSize:11,color:accent}}>ANNOUNCEMENTS</b>{s.showAnnouncements!==false?(anns.length?anns.slice(0,3).map((a:any,i:number)=><div key={a.id||i} style={{marginTop:8,fontSize:10}}><strong>{a.title}</strong><div style={{opacity:.82}}>{a.body}</div></div>):<div style={{marginTop:10}}>No announcements</div>):<div style={{marginTop:10}}>Hidden</div>}</button><button onClick={()=>setPart("donation")} style={{...selectStyle("donation"),border:`1px solid ${accent}`,borderRadius:12,background:card,color:text,padding:10,textAlign:"center"}}><b style={{fontSize:10,color:accent}}>{s.donationLabel||"Support your Masjid"}</b><div style={{fontSize:34,margin:"14px 0"}}>▦</div><small>{s.websiteUrl||"Add website link"}</small></button></div>
    </div>
    <button onClick={()=>setPart("appearance")} style={{...selectStyle("appearance"),border:0,borderTop:`1px solid ${accent}`,background:card,color:text,fontWeight:800,fontSize:10}}>Powered by Hassoun · click to edit colors & layout</button>
  </div>};

  const Editor=()=>{if(!remote)return null;const s=remote.settings;const wrap={display:"grid",gap:12} as const;switch(part){
    case "identity":return <div style={wrap}><h3 style={{margin:0}}>Mosque & display identity</h3><label>Display name<input value={remote.name} onChange={e=>updateName(e.target.value)} style={fieldStyle}/></label><label>Mosque name<input value={String(s.mosqueName||"")} onChange={e=>updateSetting("mosqueName",e.target.value)} style={fieldStyle}/></label><label>Mosque location<input value={String(s.mosqueLocation||"")} onChange={e=>updateSetting("mosqueLocation",e.target.value)} style={fieldStyle}/></label><label>Logo URL<input value={String(s.logoUrl||"")} onChange={e=>updateSetting("logoUrl",e.target.value)} placeholder="https://…" style={fieldStyle}/></label>{bool("showLogo","Show logo")}{bool("showLocation","Show location")}</div>;
    case "clock":return <div style={wrap}><h3 style={{margin:0}}>Clock & date</h3>{bool("showClock","Show clock")}{bool("showDate","Show date")}<p style={{color:"#9bb5ad",margin:0}}>The live clock uses the display device’s local time.</p></div>;
    case "next":return <div style={wrap}><h3 style={{margin:0}}>Next prayer</h3>{bool("showNextPrayer","Show next-prayer bar")}{bool("showIqama","Show Iqama")}<p style={{color:"#9bb5ad",margin:0}}>Prayer time is taken from the display’s prayer schedule. Iqama values can be edited in Prayer table.</p></div>;
    case "prayers":return <div style={wrap}><h3 style={{margin:0}}>Prayer table & Iqama</h3>{bool("showPrayerCards","Show prayer table/cards")}{bool("showIqama","Show Iqama")}{prayers.map(p=><label key={p}>{prayerLabels[p]} Iqama<input value={String(s.iqama?.[p]||"")} onChange={e=>updateIqama(p,e.target.value)} placeholder="e.g. 6:00 AM" style={fieldStyle}/></label>)}</div>;
    case "announcements":return <div style={wrap}><h3 style={{margin:0}}>Announcements</h3>{bool("showAnnouncements","Show announcements")}{announcements(s).map((a:any,i:number)=><div key={a.id||i} style={{padding:12,border:"1px solid #46675e",borderRadius:12,display:"grid",gap:8}}><input value={String(a.title||"")} onChange={e=>updateAnnouncement(i,"title",e.target.value)} placeholder="Title" style={fieldStyle}/><textarea value={String(a.body||"")} onChange={e=>updateAnnouncement(i,"body",e.target.value)} placeholder="Details" style={{...fieldStyle,minHeight:72,resize:"vertical"}}/><button onClick={()=>removeAnnouncement(i)} style={{justifySelf:"start",padding:"7px 10px",borderRadius:999,border:"1px solid #8c5c59",background:"transparent",color:"#ffd7d4"}}>Remove</button></div>)}<button onClick={addAnnouncement} style={{padding:"10px 13px",borderRadius:999,border:"1px solid #d9b36b",background:"#d9b36b",color:"#102c25",fontWeight:900}}>+ Add announcement</button></div>;
    case "verse":return <div style={wrap}><h3 style={{margin:0}}>Qur’an verse / reminder</h3>{bool("showVerse","Show verse")}<label>Verse / reminder<textarea value={String(s.verseText||"")} onChange={e=>updateSetting("verseText",e.target.value)} style={{...fieldStyle,minHeight:95,resize:"vertical"}}/></label></div>;
    case "donation":return <div style={wrap}><h3 style={{margin:0}}>Donation / website panel</h3>{bool("showDonation","Show donation panel")}<label>Panel heading<input value={String(s.donationLabel||"")} onChange={e=>updateSetting("donationLabel",e.target.value)} style={fieldStyle}/></label><label>Website / donation link<input value={String(s.websiteUrl||"")} onChange={e=>updateSetting("websiteUrl",e.target.value)} style={fieldStyle}/></label></div>;
    default:return <div style={wrap}><h3 style={{margin:0}}>Layout & appearance</h3><label>Layout<select value={String(s.layout||"grand")} onChange={e=>updateSetting("layout",e.target.value)} style={fieldStyle}><option value="grand">Grand</option><option value="community">Community</option><option value="announcements">Announcements</option><option value="cinematic">Cinematic</option><option value="board">Prayer Board</option><option value="jumuah">Jumu’ah</option><option value="adaptive">Adaptive</option><option value="minimal">Minimal</option></select></label><label>Background color<input type="color" value={color(s.backgroundColor,"#063d34")} onChange={e=>updateSetting("backgroundColor",e.target.value)} style={{...fieldStyle,height:44,padding:4}}/></label><label>Card color<input type="color" value={color(s.cardColor,"#0a5548")} onChange={e=>updateSetting("cardColor",e.target.value)} style={{...fieldStyle,height:44,padding:4}}/></label><label>Accent color<input type="color" value={color(s.accentColor,"#e7bd59")} onChange={e=>updateSetting("accentColor",e.target.value)} style={{...fieldStyle,height:44,padding:4}}/></label><label>Text color<input type="color" value={color(s.textColor,"#ffffff")} onChange={e=>updateSetting("textColor",e.target.value)} style={{...fieldStyle,height:44,padding:4}}/></label></div>;
  }};

  return <main style={{minHeight:"100vh",background:"#061f1b",color:"#f7f5eb",padding:"30px 18px",fontFamily:"Arial,sans-serif"}}><section style={{maxWidth:1180,margin:"0 auto"}}><div style={{fontSize:12,letterSpacing:2,color:"#d9b36b",fontWeight:900}}>HASSOUN</div><h1 style={{margin:"7px 0"}}>Displays</h1><p style={{color:"#c4d2cd",marginBottom:20}}>Pair and remotely manage TVs, mosque screens, tablets, office displays, or computer browsers. Select a display, then click any area in its preview to edit it live.</p>{items.length===0?<div style={{padding:22,border:"1px solid #46675e",borderRadius:16,background:"#0b322c"}}>No displays paired yet. <a href="/masjid-tv/pair/" style={{color:"#fff0bd",fontWeight:900}}>Pair a display</a>.</div>:<div style={{display:"grid",gap:12}}>{items.map(item=><article key={item.id} style={{padding:18,border:`1px solid ${editing===item.id?"#efc66c":"#826f45"}`,borderRadius:16,background:"#0b3b33"}}><div style={{display:"flex",gap:14,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap"}}><div style={{minWidth:220,flex:1}}><div style={{fontSize:19,fontWeight:900}}>{item.name}</div><div style={{fontSize:12,color:"#9bb5ad",marginTop:8}}>ID {item.id.slice(0,8).toUpperCase()}…{item.id.slice(-4).toUpperCase()} · paired {new Date(item.pairedAt).toLocaleDateString()}</div></div><div style={{fontSize:22,letterSpacing:4,fontWeight:900,color:"#efc66c"}}>{item.code}</div><button onClick={()=>load(item)} style={{padding:"10px 15px",borderRadius:999,border:"1px solid #d9b36b",background:"#d9b36b",color:"#102c25",fontWeight:900}}>Manage live</button><button onClick={()=>remove(item.id)} style={{padding:"9px 13px",borderRadius:999,border:"1px solid #8c5c59",background:"transparent",color:"#ffd7d4",fontWeight:800}}>Remove</button></div></article>)}</div>}

  {editing?<section style={{marginTop:22,padding:20,border:"1px solid #826f45",borderRadius:18,background:"#0b322c"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Live display editor</h2><div style={{fontSize:12,color:"#9bb5ad",marginTop:5}}>Click an area of the mini display to edit it. Changes auto-save.</div></div><button onClick={()=>{setEditing("");setRemote(null);setMessage("")}} style={{padding:"8px 12px",borderRadius:999,border:"1px solid #56776e",background:"transparent",color:"#fff"}}>Close</button></div>{busy&&!remote?<p>Loading…</p>:null}{remote?<div style={{display:"grid",gridTemplateColumns:"minmax(0,1.65fr) minmax(280px,.75fr)",gap:18,marginTop:18,alignItems:"start"}}><div><Preview/><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:10,fontSize:12,color:"#9bb5ad"}}><span>Revision {remote.revision}</span><span>{remote.lastSeenAt?`Display last seen ${new Date(remote.lastSeenAt).toLocaleString()}`:"Waiting for display heartbeat"}</span></div></div><aside style={{padding:16,border:"1px solid #46675e",borderRadius:14,background:"#082b26"}}><Editor/></aside></div>:null}{message?<p style={{color:message.startsWith("Live")?"#aee5bf":message.startsWith("Updating")?"#efc66c":"#ffb4ab",fontWeight:800}}>{message}</p>:null}</section>:null}

  <div style={{display:"flex",gap:16,flexWrap:"wrap",marginTop:22}}><a href="/masjid-tv/pair/" style={{color:"#fff0bd",fontWeight:900}}>Pair another display</a><a href="/more/" style={{color:"#fff0bd",fontWeight:900}}>Back to More</a><a href="/masjid-tv/" style={{color:"#fff0bd",fontWeight:900}}>Open Masjid TV</a></div></section></main>
}
