"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

const API="https://wopt-prayer-push.wopt-windsor.workers.dev";
const TOKEN_KEY="wopt:admin-token:v1";
type Overview={teachers:number;classes:number;students:number;parents:number;assignments:number;awaitingReview:number};
type Teacher={public_id:string;name:string;email?:string;phone?:string;status:string};
type ClassRow={public_id:string;name:string;invite_code:string;teacher_public_id?:string;teacher_name?:string;student_count:number;status:string;schedule_text?:string;delivery_mode:string};
type Student={public_id:string;name:string;email?:string;phone?:string;status:string;class_public_id?:string;class_name?:string;current_surah?:number;current_ayah?:number;streak:number;stars:number};

async function api<T>(path:string,token:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("Authorization",`Bearer ${token}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h});const p=await r.json().catch(()=>({})) as T&{error?:string};if(!r.ok)throw new Error(p.error||`Request failed (${r.status})`);return p}

export default function SchoolAdmin(){
 const[token,setToken]=useState("");const[tab,setTab]=useState<"overview"|"teachers"|"classes"|"students">("overview");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const[overview,setOverview]=useState<Overview>({teachers:0,classes:0,students:0,parents:0,assignments:0,awaitingReview:0});const[teachers,setTeachers]=useState<Teacher[]>([]);const[classes,setClasses]=useState<ClassRow[]>([]);const[students,setStudents]=useState<Student[]>([]);
 const[teacherName,setTeacherName]=useState("");const[teacherEmail,setTeacherEmail]=useState("");const[className,setClassName]=useState("");const[classTeacher,setClassTeacher]=useState("");const[studentName,setStudentName]=useState("");const[studentEmail,setStudentEmail]=useState("");const[studentClass,setStudentClass]=useState("");
 const load=useCallback(async(t:string)=>{const[o,tt,cc,ss]=await Promise.all([api<Overview>("/admin/school/overview",t),api<{teachers:Teacher[]}>("/admin/school/teachers",t),api<{classes:ClassRow[]}>("/admin/school/classes",t),api<{students:Student[]}>("/admin/school/students",t)]);setOverview(o);setTeachers(tt.teachers||[]);setClasses(cc.classes||[]);setStudents(ss.students||[])},[]);
 useEffect(()=>{const t=localStorage.getItem(TOKEN_KEY)||"";setToken(t);if(t)void load(t).catch(e=>setError(e instanceof Error?e.message:"Unable to load School CRM"))},[load]);
 async function run(fn:()=>Promise<void>,msg:string){setError("");try{await fn();setNotice(msg);await load(token)}catch(e){setError(e instanceof Error?e.message:"Request failed")}}
 if(!token)return <main style={s.center}><div style={s.card}><h1>Qur’an School CRM</h1><p>Please sign in to the Owner Control Center first.</p><a href="/admin/">Open Admin</a></div></main>;
 const addTeacher=(e:FormEvent)=>{e.preventDefault();void run(async()=>{await api("/admin/school/teachers",token,{method:"POST",body:JSON.stringify({name:teacherName,email:teacherEmail})});setTeacherName("");setTeacherEmail("")},"Teacher added")};
 const addClass=(e:FormEvent)=>{e.preventDefault();void run(async()=>{await api("/admin/school/classes",token,{method:"POST",body:JSON.stringify({name:className,teacherPublicId:classTeacher})});setClassName("");setClassTeacher("")},"Class added")};
 const addStudent=(e:FormEvent)=>{e.preventDefault();void run(async()=>{await api("/admin/school/students",token,{method:"POST",body:JSON.stringify({name:studentName,email:studentEmail,classPublicId:studentClass})});setStudentName("");setStudentEmail("")},"Student added")};
 return <main style={s.page}>
  <header style={s.header}><a href="/admin/" style={s.brand}><img src="/hassoun-logo.png?v=20260824-5" style={s.logo} alt="Hassoun"/><div><small style={s.eyebrow}>HASSOUN ADMIN CRM</small><strong>Qur’an School Control Center</strong></div></a><a href="/admin/" style={s.secondary}>← Main CRM</a></header>
  <section style={s.hero}><div><small style={s.eyebrow}>CENTRALIZED SCHOOL</small><h1 style={s.title}>Teachers, classes and students now live in the shared database.</h1><p>Changes made here are no longer tied to one browser or one computer.</p></div></section>
  {error?<div style={s.error}>{error}</div>:null}{notice?<div style={s.notice}>{notice}</div>:null}
  <section style={s.stats}>{[["Teachers",overview.teachers],["Classes",overview.classes],["Students",overview.students],["Parents",overview.parents],["Assignments",overview.assignments],["Awaiting review",overview.awaitingReview]].map(([l,v])=><div style={s.stat} key={String(l)}><strong>{v}</strong><span>{l}</span></div>)}</section>
  <nav style={s.tabs}>{(["overview","teachers","classes","students"] as const).map(x=><button key={x} onClick={()=>setTab(x)} style={{...s.tab,...(tab===x?s.active:{})}}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {tab==="overview"?<section style={s.grid}><div style={s.card}><h2>What is centralized</h2><p>Teachers, classes, student enrollment, status, memorization position, streaks and stars are now stored server-side.</p></div><div style={s.card}><h2>Next School modules</h2><p>Parents, assignments/review, attendance, memorization history, reports and communications are the next connected modules.</p></div></section>:null}
  {tab==="teachers"?<section style={s.grid}><form style={s.card} onSubmit={addTeacher}><h2>Add teacher</h2><input style={s.input} placeholder="Teacher name" value={teacherName} onChange={e=>setTeacherName(e.target.value)} required/><input style={s.input} placeholder="Email" value={teacherEmail} onChange={e=>setTeacherEmail(e.target.value)}/><button style={s.primary}>Add teacher</button></form><div style={s.card}><h2>Teachers</h2>{teachers.map(t=><div style={s.row} key={t.public_id}><div><strong>{t.name}</strong><small>{t.email||"No email"}</small></div><span>{t.status}</span></div>)}</div></section>:null}
  {tab==="classes"?<section style={s.grid}><form style={s.card} onSubmit={addClass}><h2>Create class</h2><input style={s.input} placeholder="Class name" value={className} onChange={e=>setClassName(e.target.value)} required/><select style={s.input} value={classTeacher} onChange={e=>setClassTeacher(e.target.value)}><option value="">No teacher yet</option>{teachers.map(t=><option key={t.public_id} value={t.public_id}>{t.name}</option>)}</select><button style={s.primary}>Create class</button></form><div style={s.card}><h2>Classes</h2>{classes.map(c=><div style={s.row} key={c.public_id}><div><strong>{c.name}</strong><small>{c.teacher_name||"No teacher"} · Code {c.invite_code}</small></div><span>{c.student_count||0} students</span></div>)}</div></section>:null}
  {tab==="students"?<section style={s.grid}><form style={s.card} onSubmit={addStudent}><h2>Add student</h2><input style={s.input} placeholder="Student name" value={studentName} onChange={e=>setStudentName(e.target.value)} required/><input style={s.input} placeholder="Email (optional)" value={studentEmail} onChange={e=>setStudentEmail(e.target.value)}/><select style={s.input} value={studentClass} onChange={e=>setStudentClass(e.target.value)}><option value="">Unassigned</option>{classes.map(c=><option key={c.public_id} value={c.public_id}>{c.name}</option>)}</select><button style={s.primary}>Add student</button></form><div style={s.card}><h2>Students</h2>{students.map(st=><div style={s.row} key={st.public_id}><div><strong>{st.name}</strong><small>{st.class_name||"No class"} · {st.email||"No email"}</small></div><span>{st.stars||0} ⭐</span></div>)}</div></section>:null}
 </main>
}

const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f6f2e8",color:"#173f35",fontFamily:"Arial,sans-serif",paddingBottom:40},center:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f6f2e8",fontFamily:"Arial,sans-serif"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px clamp(18px,4vw,48px)",background:"#fff",borderBottom:"1px solid #ddd8cc",position:"sticky",top:0,zIndex:10},brand:{display:"flex",alignItems:"center",gap:10,textDecoration:"none",color:"inherit"},logo:{width:48,height:48,objectFit:"contain",borderRadius:12},eyebrow:{display:"block",fontSize:10,fontWeight:900,letterSpacing:".14em",color:"#0d8a6d"},hero:{width:"min(1180px,calc(100% - 28px))",margin:"22px auto",background:"linear-gradient(135deg,#0d614e,#153d35)",color:"white",borderRadius:26,padding:"28px clamp(22px,4vw,44px)"},title:{fontSize:"clamp(30px,4vw,48px)",lineHeight:1.05,margin:"8px 0"},stats:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto 16px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10},stat:{background:"white",border:"1px solid #ddd8cc",borderRadius:16,padding:16,display:"grid",gap:4},tabs:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto 16px",display:"flex",gap:8,flexWrap:"wrap"},tab:{border:"1px solid #cdd9d5",background:"white",padding:"10px 14px",borderRadius:12,fontWeight:800,color:"#31574d"},active:{background:"#0b735b",color:"white"},grid:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14},card:{background:"white",border:"1px solid #ddd8cc",borderRadius:18,padding:18,display:"grid",gap:10},input:{width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #cdd9d5",borderRadius:10,background:"white"},primary:{border:0,background:"#0b735b",color:"white",fontWeight:800,padding:"11px 14px",borderRadius:10},secondary:{border:"1px solid #cdd9d5",background:"white",color:"#0b5b47",fontWeight:800,padding:"10px 13px",borderRadius:10,textDecoration:"none"},row:{display:"flex",justifyContent:"space-between",gap:12,padding:"10px 0",borderBottom:"1px solid #eee9df"},error:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto 12px",background:"#fdecec",padding:12,borderRadius:10},notice:{width:"min(1180px,calc(100% - 28px))",margin:"0 auto 12px",background:"#e9f7ef",padding:12,borderRadius:10}}
