"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

const API=(process.env.NEXT_PUBLIC_PUSH_API_URL||"https://wopt-prayer-push.wopt-windsor.workers.dev").replace(/\/$/,"");
const TOKEN_KEY="wopt:admin-token:v1";
const META:Record<string,{icon:string;name:string}>={trivia:{icon:"⚡",name:"Live Trivia"},imposter:{icon:"🕵️",name:"Imposter"},clue:{icon:"🎯",name:"Clue Battle"},wordrace:{icon:"✍️",name:"Insan • Haiwan • Shiee"},wordpuzzle:{icon:"🧩",name:"Word Puzzle"}};
type Setting={game_type:string;enabled:number;max_rounds:number;updated_at:string};
type Active={code:string;game_type:string;category:string;status:string;created_at:string;updated_at:string;state_json:string;player_count:number;top_score:number};
type Result={id:number;room_code:string;game_type:string;category:string;winner_names:string;scores_json:string;rounds_played:number;ended_reason:string;created_at:string};
type Payload={settings:Setting[];activeRooms:Active[];recentResults:Result[];totals:Array<{game_type:string;total:number}>};
async function call<T>(path:string,token:string,init?:RequestInit){const r=await fetch(`${API}${path}`,{...init,headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`,...(init?.headers||{})}});const p=await r.json().catch(()=>({})) as T&{error?:string};if(!r.ok)throw new Error(p.error||`Request failed (${r.status})`);return p}

export default function AdminGames(){
 const[token,setToken]=useState(""),[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async(t:string)=>{setError("");try{setData(await call<Payload>("/admin/games",t))}catch(e){setError(e instanceof Error?e.message:"Unable to load games")}},[]);
 useEffect(()=>{const t=localStorage.getItem(TOKEN_KEY)||"";setToken(t);if(t)void load(t)},[load]);
 const totalPlayed=useMemo(()=>data?.totals.reduce((n,x)=>n+Number(x.total||0),0)||0,[data]);
 async function save(s:Setting,patch:Partial<{enabled:boolean;maxRounds:number}>){if(!token)return;setBusy(s.game_type);try{await call(`/admin/games/settings/${s.game_type}`,token,{method:"POST",body:JSON.stringify({enabled:patch.enabled??Boolean(s.enabled),maxRounds:patch.maxRounds??s.max_rounds})});await load(token)}catch(e){setError(e instanceof Error?e.message:"Unable to save") }finally{setBusy("")}}
 async function closeRoom(code:string){if(!token||!confirm(`Close room ${code} and save its current result?`))return;setBusy(code);try{await call(`/admin/games/rooms/${code}/close`,token,{method:"POST"});await load(token)}catch(e){setError(e instanceof Error?e.message:"Unable to close room")}finally{setBusy("")}}
 if(!token)return <main style={s.page}><section style={s.card}><h1 style={s.h1}>🎮 Games</h1><p>Sign in through Owner Control Center first.</p></section></main>;
 return <main style={s.page}>
  <header style={s.hero}><div><div style={s.eyebrow}>HASSOUN ADMIN • GAMES</div><h1 style={s.h1}>🎮 Games Control Center</h1><p style={s.muted}>Control availability, round limits, active rooms, winners and saved match history.</p></div><button style={s.refresh} onClick={()=>void load(token)}>↻ Refresh</button></header>
  {error?<div style={s.error}>{error}</div>:null}
  <section style={s.stats}><div style={s.stat}><b>{data?.activeRooms.length||0}</b><span>Active rooms</span></div><div style={s.stat}><b>{totalPlayed}</b><span>Completed matches</span></div><div style={s.stat}><b>{data?.settings.filter(x=>x.enabled).length||0}/5</b><span>Games enabled</span></div></section>
  <section style={s.card}><div style={s.sectionHead}><div><div style={s.eyebrow}>GAME SETTINGS</div><h2 style={s.h2}>Availability & automatic endings</h2></div></div><div style={s.grid}>{(data?.settings||[]).map(g=>{const m=META[g.game_type]||{icon:"🎮",name:g.game_type};return <article key={g.game_type} style={s.game}><div style={s.gameTop}><span style={s.icon}>{m.icon}</span><div style={{flex:1}}><strong>{m.name}</strong><small style={s.small}>{g.game_type==="wordrace"?"Insan • Haiwan • Nabat • Jamad • Balad":g.game_type==="wordpuzzle"?"Timed word puzzles":"Multiplayer"}</small></div><button onClick={()=>void save(g,{enabled:!g.enabled})} disabled={busy===g.game_type} style={{...s.toggle,background:g.enabled?"#0b654f":"#ddd",color:g.enabled?"white":"#555"}}>{g.enabled?"Enabled":"Disabled"}</button></div><label style={s.label}>Rounds before automatic winner<input type="number" min={1} max={20} value={g.max_rounds} onChange={e=>void save(g,{maxRounds:Number(e.target.value)})} style={s.input}/></label></article>})}</div></section>
  <section style={s.card}><div style={s.sectionHead}><div><div style={s.eyebrow}>LIVE</div><h2 style={s.h2}>Active rooms</h2></div></div>{!data?.activeRooms.length?<p style={s.muted}>No active rooms right now.</p>:<div style={s.tableWrap}><table style={s.table}><thead><tr><th>Room</th><th>Game</th><th>Players</th><th>Top score</th><th>Status</th><th></th></tr></thead><tbody>{data.activeRooms.map(r=><tr key={r.code}><td><b>{r.code}</b></td><td>{META[r.game_type]?.icon} {META[r.game_type]?.name||r.game_type}</td><td>{r.player_count}</td><td>{r.top_score}</td><td>{r.status}</td><td><button style={s.danger} disabled={busy===r.code} onClick={()=>void closeRoom(r.code)}>Close & save</button></td></tr>)}</tbody></table></div>}</section>
  <section style={s.card}><div style={s.sectionHead}><div><div style={s.eyebrow}>RESULTS</div><h2 style={s.h2}>Recent completed games</h2></div></div>{!data?.recentResults.length?<p style={s.muted}>No completed matches yet.</p>:<div style={s.results}>{data.recentResults.map(r=>{let scores:Array<{name:string;score:number}>=[];try{scores=JSON.parse(r.scores_json)}catch{}return <article key={r.id} style={s.result}><div style={s.resultTop}><div><strong>{META[r.game_type]?.icon} {META[r.game_type]?.name||r.game_type}</strong><small style={s.small}>Room {r.room_code} • {r.rounds_played} rounds • {new Date(r.created_at).toLocaleString()}</small></div><span style={s.win}>🏆 {r.winner_names||"No winner"}</span></div><div style={s.scoreRow}>{scores.map((p,i)=><span key={`${p.name}-${i}`} style={s.scoreChip}>{p.name} <b>{p.score}</b></span>)}</div></article>})}</div>}</section>
 </main>
}

const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f7f5ef",padding:"28px",color:"#173f35",fontFamily:"system-ui,sans-serif"},hero:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:18},eyebrow:{fontSize:11,fontWeight:900,letterSpacing:".12em",color:"#a17c36"},h1:{fontSize:34,margin:"5px 0"},h2:{fontSize:22,margin:"4px 0"},muted:{color:"#71807a"},refresh:{border:0,borderRadius:12,padding:"12px 16px",background:"#0b654f",color:"white",fontWeight:800,cursor:"pointer"},error:{background:"#fff0ed",border:"1px solid #efc5be",color:"#9b3429",padding:12,borderRadius:12,marginBottom:14},stats:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginBottom:14},stat:{background:"white",border:"1px solid #e2ded4",borderRadius:18,padding:18,display:"grid",gap:4},card:{background:"white",border:"1px solid #e2ded4",borderRadius:22,padding:20,marginBottom:15,boxShadow:"0 6px 20px rgba(35,68,57,.05)"},sectionHead:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:10},game:{border:"1px solid #e5e1d8",borderRadius:17,padding:14,background:"#fbfaf6"},gameTop:{display:"flex",alignItems:"center",gap:10},icon:{fontSize:30},small:{display:"block",color:"#7b8782",marginTop:3},toggle:{border:0,borderRadius:99,padding:"8px 11px",fontWeight:800,cursor:"pointer"},label:{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:13},input:{border:"1px solid #d8d6cf",borderRadius:10,padding:"9px 10px",fontSize:15},tableWrap:{overflowX:"auto"},table:{width:"100%",borderCollapse:"collapse"},danger:{border:"1px solid #efc5be",background:"#fff0ed",color:"#9b3429",borderRadius:9,padding:"7px 9px",fontWeight:800,cursor:"pointer"},results:{display:"grid",gap:10},result:{border:"1px solid #e5e1d8",borderRadius:16,padding:14},resultTop:{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start"},win:{background:"#edf5f1",borderRadius:99,padding:"7px 10px",fontWeight:850},scoreRow:{display:"flex",gap:6,flexWrap:"wrap",marginTop:10},scoreChip:{background:"#f4f2ec",padding:"6px 9px",borderRadius:99,fontSize:12}}
