import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import BrandMark from "./BrandMark";

type Locale = "en" | "ar";
type Item = { emoji:string; en:string; ar:string; whatEn:string; whatAr:string; stepsEn:string[]; stepsAr:string[]; exampleEn:string; exampleAr:string; tipEn:string; tipAr:string; tags:string };

const ITEMS: Item[] = [
 {emoji:"🕌",en:"Prayer times & GPS",ar:"مواقيت الصلاة والموقع",whatEn:"Uses your current location for local prayer times. Windsor uses the trusted Windsor schedule; other locations use location-based calculation.",whatAr:"يستخدم موقعك الحالي لمواقيت الصلاة المحلية. وندسور تستخدم الجدول الموثوق وبقية المدن تستخدم الحساب حسب الموقع.",stepsEn:["Allow Location.","Open Home and confirm the location.","Prayer cards and countdown update automatically."],stepsAr:["اسمح بالموقع.","افتح الرئيسية وتأكد من الموقع.","تتحدث بطاقات الصلاة والعد التنازلي تلقائياً."],exampleEn:"Travel Windsor → Toronto: reopen Hassoun and Toronto times should appear.",exampleAr:"سافر من وندسور إلى تورونتو: افتح Hassoun لتظهر مواقيت تورونتو.",tipEn:"📍 Wrong city? Check Settings → Permissions → Location.",tipAr:"📍 مدينة خاطئة؟ تحقق من الإعدادات ← الأذونات ← الموقع.",tags:"prayer gps location travel adhan"},
 {emoji:"🔔",en:"Adhan & reminders",ar:"الأذان والتنبيهات",whatEn:"Choose 20-minute, 10-minute and prayer-time alerts. Android exact alarms help Adhan start at the scheduled time.",whatAr:"اختر تنبيه 20 دقيقة و10 دقائق ووقت الصلاة. تساعد منبهات أندرويد الدقيقة على تشغيل الأذان في وقته.",stepsEn:["Settings → Prayer & Adhan alerts.","Enable the reminders you want.","Allow Notifications and Alarms & reminders."],stepsAr:["الإعدادات ← تنبيهات الصلاة والأذان.","فعّل التنبيهات المطلوبة.","اسمح بالتنبيهات والمنبهات والتذكيرات."],exampleEn:"Fajr 5:20 + 10-minute reminder → reminder near 5:10, then Adhan at prayer time if enabled.",exampleAr:"الفجر 5:20 مع تنبيه 10 دقائق ← تنبيه قرابة 5:10 ثم الأذان وقت الصلاة إذا كان مفعلاً.",tipEn:"⏰ Exact-alarm permission matters when the screen is locked.",tipAr:"⏰ إذن المنبه الدقيق مهم عند قفل الشاشة.",tags:"alarm notification adhan fajr"},
 {emoji:"📖",en:"Qur’an reader",ar:"قارئ القرآن",whatEn:"Read by Surah, Juz or Mushaf page, search, bookmark, listen and customize Tajweed, font and browsing direction.",whatAr:"اقرأ حسب السورة أو الجزء أو صفحة المصحف وابحث واحفظ واستمع وخصص التجويد والخط واتجاه التصفح.",stepsEn:["Open Qur’an.","Choose Surahs, Juz, Pages, Search or Bookmarks.","Open Appearance for Tajweed, font, vertical or horizontal browsing."],stepsAr:["افتح القرآن.","اختر السور أو الأجزاء أو الصفحات أو البحث أو العلامات.","افتح المظهر للتجويد والخط والتصفح العمودي أو الأفقي."],exampleEn:"Page 10 → move forward to 11 or backward to 9.",exampleAr:"الصفحة 10 ← انتقل للأمام إلى 11 أو للخلف إلى 9.",tipEn:"🎧 Tap an ayah for audio, repeat, bookmark and study tools.",tipAr:"🎧 اضغط على آية للصوت والتكرار والحفظ وأدوات الدراسة.",tags:"quran surah juz tajweed audio bookmark"},
 {emoji:"🎓",en:"Al-Hafiz memorization",ar:"الحافظ للحفظ",whatEn:"Create saved lessons from a Surah, ayah range, Mushaf page or passage, then split them into easy study cards.",whatAr:"أنشئ دروساً محفوظة من سورة أو آيات أو صفحة مصحف أو مقطع ثم قسمها إلى بطاقات سهلة.",stepsEn:["Qur’an → Memorize / Al-Hafiz.","Create or import a lesson.","Tap Make Cards.","Listen, study, test a card or test the whole lesson."],stepsAr:["القرآن ← الحفظ / الحافظ.","أنشئ أو استورد درساً.","اضغط إنشاء بطاقات.","استمع وادرس ثم اختبر بطاقة أو الدرس كاملاً."],exampleEn:"10 lines can become 3 balanced cards for easier memorization.",exampleAr:"يمكن تقسيم 10 أسطر إلى 3 بطاقات متوازنة لتسهيل الحفظ.",tipEn:"⭐ Earn stars and badges; the AI Teacher recommends what to review next.",tipAr:"⭐ اكسب النجوم والشارات ويقترح المعلم الذكي ما تراجعه بعد ذلك.",tags:"hafiz memorize kids cards ai lesson"},
 {emoji:"🎙️",en:"Recitation testing",ar:"اختبار التلاوة",whatEn:"Hide the text, recite from memory, and review recognized words, mistakes and score.",whatAr:"أخفِ النص وتلُ من الذاكرة ثم راجع الكلمات والأخطاء والدرجة.",stepsEn:["Open an Al-Hafiz lesson.","Choose Card Test or Whole Lesson.","Allow Microphone.","Recite clearly and review your result."],stepsAr:["افتح درساً في الحافظ.","اختر اختبار بطاقة أو الدرس.","اسمح بالميكروفون.","اقرأ بوضوح وراجع النتيجة."],exampleEn:"18/20 words correct → weak words are identified for review.",exampleAr:"18 كلمة صحيحة من 20 ← تظهر الكلمات الضعيفة للمراجعة.",tipEn:"🧠 Practice weak cards before retesting the whole lesson.",tipAr:"🧠 تدرب على البطاقات الضعيفة قبل إعادة اختبار الدرس.",tags:"recitation microphone test score mistakes"},
 {emoji:"🏆",en:"Games & session history",ar:"الألعاب وسجل الجلسات",whatEn:"Play Islamic learning games and save players, score, winner, game and date as history cards.",whatAr:"العب ألعاباً تعليمية إسلامية واحفظ اللاعبين والنتيجة والفائز واللعبة والتاريخ كبطاقات سجل.",stepsEn:["Create or join a game room.","Play the game.","Host chooses End game & save results.","Open Recent Sessions later."],stepsAr:["أنشئ أو انضم لغرفة.","العب اللعبة.","يختار المضيف إنهاء اللعبة وحفظ النتائج.","افتح الجلسات الأخيرة لاحقاً."],exampleEn:"Sam vs Rama • Quiz • 8–6 • saved as a result card.",exampleAr:"سام ضد راما • مسابقة • 8–6 • تحفظ كبطاقة نتيجة.",tipEn:"🎯 Rematches make learning a friendly family challenge.",tipAr:"🎯 إعادة اللعب تحول التعلم إلى تحدٍ عائلي ممتع.",tags:"games multiplayer history quiz"},
 {emoji:"🗓️",en:"Islamic events",ar:"المناسبات الإسلامية",whatEn:"Shows the next event plus every remaining event in the current Hijri year, with earlier events separated.",whatAr:"يعرض المناسبة القادمة وكل المناسبات المتبقية في السنة الهجرية مع فصل المناسبات السابقة.",stepsEn:["Open Islamic Events.","See the next event at the top.","Scroll through Remaining events and Earlier events."],stepsAr:["افتح المناسبات الإسلامية.","شاهد المناسبة القادمة في الأعلى.","مرر خلال المتبقية والسابقة."],exampleEn:"If five events remain, all five appear—not only the nearest one.",exampleAr:"إذا بقيت خمس مناسبات فستظهر كلها وليس فقط أقرب مناسبة.",tipEn:"🌙 Moon-sighting dates can vary by a day.",tipAr:"🌙 قد تختلف تواريخ رؤية الهلال يوماً.",tags:"events hijri ramadan eid"},
 {emoji:"🧩",en:"Widgets",ar:"الويدجت",whatEn:"Keep next prayer and daily times visible on supported home and lock screens.",whatAr:"أبقِ الصلاة القادمة ومواقيت اليوم ظاهرة على الشاشات الرئيسية والقفل المدعومة.",stepsEn:["Settings → Widgets.","Choose Light, Dark or Auto.","Choose Large, Square, Vertical or Slim.","Add Hassoun from Android widgets."],stepsAr:["الإعدادات ← الويدجت.","اختر فاتح أو داكن أو تلقائي.","اختر الحجم والتصميم.","أضف Hassoun من ويدجت أندرويد."],exampleEn:"Slim shows Hassoun + next prayer in a small space.",exampleAr:"التصميم الرفيع يعرض Hassoun والصلاة القادمة في مساحة صغيرة.",tipEn:"📱 Samsung lock-screen widgets may use Good Lock / LockStar.",tipAr:"📱 قد تحتاج سامسونج إلى Good Lock / LockStar لشاشة القفل.",tags:"widget lock screen samsung"},
 {emoji:"📣",en:"Scrolling announcements",ar:"شريط الإعلانات",whatEn:"Important Hassoun messages can appear as an emoji-friendly scrolling bar when enabled by the administrator.",whatAr:"يمكن أن تظهر رسائل Hassoun المهمة كشريط متحرك يدعم الإيموجي عند تفعيله من الإدارة.",stepsEn:["No user setup is needed.","When enabled it appears automatically.","When disabled it disappears completely."],stepsAr:["لا يحتاج المستخدم إلى إعداد.","عند التفعيل يظهر تلقائياً.","عند الإيقاف يختفي بالكامل."],exampleEn:"🌙 Ramadan reminder • 📖 Read Qur’an today • 🤲 Keep us in your du‘a.",exampleAr:"🌙 تذكير رمضان • 📖 اقرأ القرآن اليوم • 🤲 لا تنسونا من الدعاء.",tipEn:"✨ Useful for alerts, events and community reminders.",tipAr:"✨ مفيد للتنبيهات والمناسبات والتذكيرات.",tags:"ticker scrolling admin announcement"},
 {emoji:"🛠️",en:"Quick troubleshooting",ar:"حل المشاكل بسرعة",whatEn:"Most setup problems come from permissions, battery restrictions or an old build.",whatAr:"معظم مشاكل الإعداد تأتي من الأذونات أو قيود البطارية أو إصدار قديم.",stepsEn:["Wrong prayer location → check Location.","Adhan missing → check Notifications + Alarms & reminders.","Recitation cannot hear you → check Microphone.","Widget stale → Settings → Widgets → Refresh.","Feature missing → install the latest Hassoun version."],stepsAr:["موقع الصلاة خطأ ← تحقق من الموقع.","الأذان لا يعمل ← تحقق من التنبيهات والمنبهات.","التلاوة لا تسمعك ← تحقق من الميكروفون.","الويدجت قديم ← الإعدادات ← الويدجت ← تحديث.","ميزة مفقودة ← ثبت أحدث إصدار Hassoun."],exampleEn:"Adhan works only after exact alarms are enabled → Settings → Permissions → Alarms & reminders.",exampleAr:"الأذان يعمل بعد تفعيل المنبهات الدقيقة ← الإعدادات ← الأذونات ← المنبهات والتذكيرات.",tipEn:"🆘 Still stuck? Settings → Contact us.",tipAr:"🆘 ما زالت المشكلة؟ الإعدادات ← اتصل بنا.",tags:"help support permission troubleshooting"}
];

export default function FeatureGuidePage({locale,onBack}:{locale:Locale;onBack:()=>void}) {
 const ar=locale==="ar"; const t=(en:string,arText:string)=>ar?arText:en; const [query,setQuery]=useState(""); const [open,setOpen]=useState<string|null>(null);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); return !q?ITEMS:ITEMS.filter(x=>`${x.en} ${x.ar} ${x.whatEn} ${x.whatAr} ${x.tags}`.toLowerCase().includes(q));},[query]);
 return <ScrollView style={s.flex} contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}>
  <View style={s.header}><Pressable onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></Pressable><BrandMark size={46}/><View style={s.copy}><Text style={s.eyebrow}>✨ HASSOUN</Text><Text style={s.title}>{t("Learn the App","تعرّف على التطبيق")}</Text></View></View>
  <View style={s.hero}><Text style={s.heroEmoji}>🧭</Text><View style={s.copy}><Text style={s.heroTitle}>{t("Your smart Hassoun guide","دليلك الذكي إلى Hassoun")}</Text><Text style={s.heroText}>{t("Search any feature, learn what it does, follow easy steps and see real examples.","ابحث عن أي ميزة واعرف ماذا تفعل واتبع خطوات سهلة وشاهد أمثلة حقيقية.")}</Text></View></View>
  <TextInput value={query} onChangeText={setQuery} placeholder={t("🔎 Search: Adhan, Qur’an, GPS, games…","🔎 ابحث: الأذان، القرآن، الموقع، الألعاب…")} placeholderTextColor="#89958f" style={[s.search,ar&&s.rtl]}/>
  <View style={s.start}><Text style={s.startTitle}>{t("🚀 Start here","🚀 ابدأ من هنا")}</Text><Text style={s.startText}>{t("Best setup: Location 📍 + Notifications 🔔 + Alarms ⏰. Microphone 🎙️ is only needed for recitation testing.","أفضل إعداد: الموقع 📍 + التنبيهات 🔔 + المنبهات ⏰. الميكروفون 🎙️ مطلوب فقط لاختبار التلاوة.")}</Text></View>
  {filtered.map(item=>{const id=item.en,expanded=open===id,steps=ar?item.stepsAr:item.stepsEn;return <Pressable key={id} onPress={()=>setOpen(expanded?null:id)} style={s.card}><View style={s.row}><View style={s.icon}><Text style={s.iconText}>{item.emoji}</Text></View><View style={s.copy}><Text style={[s.cardTitle,ar&&s.rtl]}>{ar?item.ar:item.en}</Text><Text style={[s.cardWhat,ar&&s.rtl]}>{ar?item.whatAr:item.whatEn}</Text></View><Text style={s.chev}>{expanded?"⌃":"⌄"}</Text></View>{expanded?<View style={s.details}><Text style={[s.label,ar&&s.rtl]}>{t("HOW TO USE IT","طريقة الاستخدام")}</Text>{steps.map((step,i)=><Text key={`${id}-${i}`} style={[s.step,ar&&s.rtl]}>{i+1}. {step}</Text>)}<View style={s.example}><Text style={s.exampleTitle}>{t("💡 Example","💡 مثال")}</Text><Text style={[s.exampleText,ar&&s.rtl]}>{ar?item.exampleAr:item.exampleEn}</Text></View><Text style={[s.tip,ar&&s.rtl]}>{ar?item.tipAr:item.tipEn}</Text></View>:null}</Pressable>})}
  {!filtered.length?<View style={s.empty}><Text style={s.emptyEmoji}>🤔</Text><Text style={s.cardTitle}>{t("Nothing matched that search","لا توجد نتيجة مطابقة")}</Text></View>:null}
  <View style={s.footer}><Text style={s.footerText}>{t("🤲 Hassoun is a Sadaqah Jariyah. Learn something useful, share it, and keep the benefit going.","🤲 Hassoun صدقة جارية. تعلّم شيئاً نافعاً وشاركه ليستمر النفع والأجر.")}</Text></View>
 </ScrollView>;
}
const s=StyleSheet.create({flex:{flex:1,backgroundColor:"#f7f4ec"},screen:{paddingHorizontal:18,paddingTop:14,paddingBottom:48},header:{flexDirection:"row",alignItems:"center",gap:10},back:{width:42,height:42,borderRadius:14,backgroundColor:"#fff",borderWidth:1,borderColor:"#dedbd2",alignItems:"center",justifyContent:"center"},backText:{fontSize:30,lineHeight:32,color:"#0b654f"},copy:{flex:1,minWidth:0},eyebrow:{color:"#a17c36",fontSize:9,fontWeight:"900",letterSpacing:1.2},title:{color:"#173f35",fontSize:25,fontWeight:"900"},hero:{marginTop:14,borderRadius:24,backgroundColor:"#075a46",padding:17,flexDirection:"row",gap:13,alignItems:"center"},heroEmoji:{fontSize:34},heroTitle:{color:"#fff",fontSize:18,fontWeight:"900"},heroText:{color:"#d6e6e0",fontSize:11.5,lineHeight:17,marginTop:4},search:{marginTop:13,borderWidth:1,borderColor:"#ddd8cd",borderRadius:17,backgroundColor:"#fff",paddingHorizontal:14,paddingVertical:12,color:"#173f35",fontSize:13},start:{marginTop:11,borderRadius:19,backgroundColor:"#fff4cf",borderWidth:1,borderColor:"#ead18a",padding:14},startTitle:{color:"#765716",fontSize:14,fontWeight:"900"},startText:{color:"#786c51",fontSize:11,lineHeight:17,marginTop:5},card:{marginTop:10,borderRadius:21,backgroundColor:"#fff",borderWidth:1,borderColor:"#e1ddd4",padding:13},row:{flexDirection:"row",gap:11,alignItems:"flex-start"},icon:{width:46,height:46,borderRadius:15,backgroundColor:"#edf4f0",alignItems:"center",justifyContent:"center"},iconText:{fontSize:23},cardTitle:{color:"#173f35",fontSize:15,fontWeight:"900"},cardWhat:{color:"#71817b",fontSize:11,lineHeight:16,marginTop:4},chev:{color:"#9d824b",fontSize:18,fontWeight:"900"},details:{borderTopWidth:1,borderTopColor:"#eeeae1",marginTop:12,paddingTop:12},label:{color:"#9a7b3f",fontSize:9,fontWeight:"900",letterSpacing:1},step:{color:"#415b53",fontSize:11.5,lineHeight:18,marginTop:5},example:{marginTop:10,borderRadius:15,backgroundColor:"#edf5f1",padding:11},exampleTitle:{color:"#17634e",fontSize:11,fontWeight:"900"},exampleText:{color:"#597068",fontSize:11,lineHeight:16,marginTop:4},tip:{color:"#765716",fontSize:11,lineHeight:17,marginTop:10,fontWeight:"700"},empty:{alignItems:"center",padding:28},emptyEmoji:{fontSize:32,marginBottom:8},footer:{marginTop:16,borderRadius:18,backgroundColor:"#e7f2ed",padding:14},footerText:{color:"#4c6b61",fontSize:11,lineHeight:17,textAlign:"center",fontWeight:"700"},rtl:{textAlign:"right",writingDirection:"rtl"}});