PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO app_settings(setting_key,value_json,description) VALUES
 ('prayer_times_enabled','true','Master switch for prayer time features.'),
 ('alerts_enabled','true','Master switch for prayer and app alerts.'),
 ('islamic_events_enabled','true','Show Islamic events and occasion features.'),
 ('school_enabled','true','Show Qur’an School features.'),
 ('ask_sheikh_enabled','true','Enable Ask the Sheikh.'),
 ('qibla_enabled','true','Enable Qibla tools.'),
 ('support_enabled','true','Enable Contact Us and support form.'),
 ('push_signup_enabled','true','Allow web/mobile push registration.'),
 ('email_signup_enabled','true','Allow email subscription signup.'),
 ('sponsor_enabled','true','Master switch for sponsor/supporter blocks.'),
 ('home_prayer_cards_enabled','true','Show prayer cards on the home screen.'),
 ('home_next_prayer_enabled','true','Show Next Prayer card and countdown.'),
 ('home_quran_enabled','true','Show Qur’an shortcuts/content on home.'),
 ('home_school_enabled','true','Show Qur’an School entry on home.'),
 ('home_games_enabled','true','Show games entry on home.'),
 ('home_support_enabled','true','Show support/contact entry on home.'),
 ('default_calculation_method','2','Default prayer calculation method when location has no saved preference.'),
 ('default_madhab','"standard"','Default Asr madhab.'),
 ('adhan_enabled','true','Master switch for Adhan audio features.'),
 ('fajr_adhan_enabled','true','Enable dedicated Fajr Adhan.'),
 ('dua_after_adhan_enabled','true','Enable Dua after Adhan where supported.'),
 ('maintenance_message','{"title":"Hassoun maintenance","message":"We’ll be back shortly."}','Maintenance screen content.'),
 ('system_banner','{"enabled":false,"title":"","message":""}','Optional app-wide banner.'),
 ('scrolling_ticker','{"enabled":false,"textEn":"","textAr":""}','Optional scrolling home ticker.');
