"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
const API="https://wopt-prayer-push.wopt-windsor.workers.dev";
const KEY="wopt:admin-token:v1";
type D={subscriber:Record<string,unknown>;emailPreferences:Record<string,unknown>;prayerPreferences:Record<string,unknown>[];devices:Record<string,unknown>[];activity:Record<string,unknown>[];recentEmailDeliveries:Record<string,unknown>[]};
async function call<T>(path:string,t:string,init:RequestInit={}):Promise<T>{const h=new Headers(init.headers);h.set("Authorization",`Bearer ${t}`);if(init.body)h.set("Content-Type","application/json");const r=await fetch(`${API}${path}`,{...init,headers:h});const p=await r.json().catch(()=>({})) as T&{error?:string};if(!r.ok)throw new Error(p.error||`Request failed (${r.status})`);return p}
export default function User360(){const params=useParams();const rawId=(params as Record<string,string|string[]>).id;const id=decodeURIComponent(Array.isArray(rawId)?rawId[0]||"":String(rawId||""));const[token,setToken]=useState("");const[data,setData]=useState<D|null>(null);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[name,setName]=useState("");const[city,setCity]=useState("");const[status,setStatus]=useState("active");const load=async(t=token)=>{const d=await call<D>(`/admin/subscribers/${encodeURIComponent(id)}/360`,t);setData(d);setName(String(d.subscriber.display_name||""));setCity(String(d.subscriber.city||""));setStatus(String(d.subscriber.status||"active"))};useEffect(()=>{const t=localStorage.getItem(KEY)||"";setToken(t);if(t)void load(t).catch(e=>setError(String((e as Error).message||e)))},[id]);const save=async()=>{if(!data)return;try{await call(`/admin/subscribers/${encodeURIComponent(id)}/profile`,token,{method:"POST",body:JSON.stringify({displayName:name,city,status,latitude:data.subscriber.latitude,longitude:data.subscriber.longitude})});setNotice("Profile saved");await load()}catch(e){setError(String((e as Error).message||e))}};if(!token)return <main style={s.center}>Sign in to Admin first.</main>;const emailLabel=data?String(data.subscriber.email||"User details"):"User details";return <main style={s.page}><header style={s.header}><div><small style={s.eye}>USER 360</small><h1>{emailLabel}</h1></div><a href="/admin/users/" style={s.link}>← Users</a></header>{error?<div style={s.err}>{error}</div>:null}{notice?<div style={s.ok}>{notice}</div>:null}{data?<><section style={s.grid}><div style={s.card}><h2>Profile</h2><label>Display name</label><input style={s.input} value={name} onChange={e=>setName(e.target.value)}/><label>City</label><input style={s.input} value={city} onChange={e=>setCity(e.target.value)}/><label>Status</label><select style={s.input} value={status} onChange={e=>setStatus(e.target.value)}>{["active","pending","unsubscribed","bounced","disabled"].map(x=><option key={x}>{x}</option>)}</select><p><strong>Timezone:</strong> {String(data.subscriber.timezone||"—")}</p><p><strong>Location:</strong> {String(data.subscriber.latitude||"—")}, {String(data.subscriber.longitude||"—")}</p><button style={s.primary} onClick={()=>void save()}>Save profile</button></div><Panel title="Email preferences" data={data.emailPreferences}/></section><section style={s.grid}><List title="Devices" rows={data.devices}/><List title="Recent activity" rows={data.activity}/><List title="Recent email deliveries" rows={data.recentEmailDeliveries}/><List title="Prayer preferences" rows={data.prayerPreferences}/></section></>:<p style={s.loading}>Loading User 360…</p>}</main>}
function Panel({title,data}:{title:string;data:Record<string,unknown>}){return <div style={s.card}><h2>{title}</h2>{Object.entries(data).map(([k,v])=><div key={k} style={s.row}><span>{k.replaceAll("_"," ")}</span><strong>{String(v==null?"—":v)}</strong></div>)}</div>}
function List({title,rows}:{title:string;rows:Record<string,unknown>[]}){return <div style={s.card}><h2>{title}</h2>{rows.slice(0,50).map((r,i)=>{const label=String(r.activity_label||r.platform||r.notification_kind||r.prayer||r.installation_id||`Record ${i+1}`);return <details key={i} style={s.detail}><summary>{label}</summary><pre style={s.pre}>{JSON.stringify(r,null,2)}</pre></details>})}{rows.length===0?<p>No records.</p>:null}</div>}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f6f2e8",color:"#173f35",paddingBottom:40},center:{minHeight:"100vh",display:"grid",placeItems:"center"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"20px clamp(18px,4vw,48px)",background:"white",borderBottom:"1px solid #ddd6c8"},eye:{fontWeight:900,letterSpacing:".14em",color:"#0b8065"},link:{textDecoration:"none",color:"#0b735b",fontWeight:800},grid:{width:"min(1180px,calc(100% - 28px))",margin:"18px auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:12},card:{background:"white",border:"1px solid #ded6c6",borderRadius:18,padding:18},input:{width:"100%",boxSizing:"border-box",padding:"10px 11px",border:"1px solid #cdd9d5",borderRadius:10,margin:"5px 0 10px"},primary:{border:0,borderRadius:10,background:"#0b735b",color:"white",padding:"11px 14px",fontWeight:800},row:{display:"flex",justifyContent:"space-between",gap:12,padding:"8px 0",borderBottom:"1px solid #eee8dd",textTransform:"capitalize"},detail:{padding:"8px 0",borderBottom:"1px solid #eee8dd"},pre:{whiteSpace:"pre-wrap",fontSize:11,overflowX:"auto"},err:{width:"min(1180px,calc(100% - 28px))",margin:"12px auto",background:"#fdecec",padding:12,borderRadius:10},ok:{width:"min(1180px,calc(100% - 28px))",margin:"12px auto",background:"#e9f7ef",padding:12,borderRadius:10},loading:{textAlign:"center"}}
