import { requireAdmin } from "./adminAuth";
import { subscriberManageUrl } from "./subscribers";
import { processEmailOutbox } from "./emailDelivery";
import type { Env, Locale } from "./types";

type Category = "religious_occasion" | "daily_content" | "announcement" | "community_event" | "marketing" | "system";
type Audience = "all_subscribers" | "custom";
type TargetLocale = "all" | "en" | "ar";
type CampaignRow = { id:number; public_id:string; name:string; template_key:string|null; category:Category; audience:Audience; target_locale:TargetLocale; target_country_code:string|null; target_city:string|null; target_timezone:string|null; status:string; scheduled_at:string|null };
type SubscriberRow = { id:number; public_id:string; email:string; locale:Locale; country_code:string|null; country_name:string|null; region:string|null; city:string|null; timezone:string; religious_occasions:number; daily_content:number; announcements:number; community_events:number; marketing:number };
type ProfileRow = Record<string, unknown> & { template_key:string; enabled:number; include_islamic_occasion:number; include_daily_hadith:number; include_daily_surah:number; include_occasion_countdown:number; include_motivation:number; include_sadaqah_jariyah:number; include_sponsor:number; sponsor_name:string|null; sponsor_url:string|null; sponsor_message_en:string|null; sponsor_message_ar:string|null };

function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}})}
async function bodyJson(request:Request){const length=Number(request.headers.get("Content-Length")??0);if(length>131072)throw new Error("Request body is too large");return await request.json() as Record<string,unknown>}
function clean(value:unknown,max:number){if(typeof value!=="string")return null;const text=value.trim();return text&&text.length<=max?text:null}
function optionalString(body:Record<string,unknown>,key:string,current:string|null,max:number){if(!(key in body))return current;if(body[key]===null||body[key]==="")return null;return clean(body[key],max)}
function normalizeUrl(value:string|null){if(!value)return null;const withScheme=/^https?:\/\//i.test(value)?value:`https://${value}`;try{const url=new URL(withScheme);return url.protocol==="https:"||url.protocol==="http:"?url.toString():null}catch{return null}}
function flag(value:unknown,fallback=0){if(value===true||value===1||value==="1")return 1;if(value===false||value===0||value==="0")return 0;return fallback}
function category(value:unknown):Category{return ["religious_occasion","daily_content","announcement","community_event","marketing","system"].includes(String(value))?value as Category:"announcement"}
function audience(value:unknown):Audience{return value==="custom"?"custom":"all_subscribers"}
function targetLocale(value:unknown):TargetLocale{return value==="en"||value==="ar"?value:"all"}
function scheduleTime(value:unknown){if(typeof value!=="string"||!value.trim())return new Date().toISOString();const parsed=Date.parse(value);return Number.isFinite(parsed)?new Date(parsed).toISOString():null}
function outboxKind(value:Category){return value==="system"?"announcement":value}
function categoryAllowed(s:SubscriberRow,c:CampaignRow){if(c.category==="system")return true;if(c.category==="religious_occasion")return s.religious_occasions===1;if(c.category==="daily_content")return s.daily_content===1;if(c.category==="community_event")return s.community_events===1;if(c.category==="marketing")return s.marketing===1;return s.announcements===1}
function matchesTarget(s:SubscriberRow,c:CampaignRow){if(!categoryAllowed(s,c))return false;if(c.target_locale!=="all"&&s.locale!==c.target_locale)return false;if(c.target_country_code&&s.country_code!==c.target_country_code)return false;if(c.target_city&&s.city?.toLowerCase()!==c.target_city.toLowerCase())return false;if(c.target_timezone&&s.timezone!==c.target_timezone)return false;return true}
async function logAdmin(env:Env,adminId:number,action:string,entityId:string,details:unknown){await env.DB.prepare(`INSERT INTO admin_activity_log (admin_user_id, action, entity_type, entity_id, details_json) VALUES (?, ?, 'email_campaign', ?, ?)`).bind(adminId,action,entityId,JSON.stringify(details??{})).run()}

async function updateTemplateProfile(env:Env,adminId:number,body:Record<string,unknown>){const key=clean(body.templateKey,120);if(!key)return json({error:"Template key is required"},400);const existing=await env.DB.prepare(`SELECT template_key, enabled, include_islamic_occasion, include_daily_hadith, include_daily_surah, include_occasion_countdown, include_motivation, include_sadaqah_jariyah, include_sponsor, sponsor_name, sponsor_url, sponsor_message_en, sponsor_message_ar FROM email_template_profiles WHERE template_key = ? LIMIT 1`).bind(key).first<ProfileRow>();if(!existing)return json({error:"Template profile not found"},404);const sponsorName=optionalString(body,"sponsorName",existing.sponsor_name,120),rawSponsorUrl=optionalString(body,"sponsorUrl",existing.sponsor_url,500),sponsorUrl=normalizeUrl(rawSponsorUrl);if("sponsorUrl" in body&&rawSponsorUrl&&!sponsorUrl)return json({error:"Sponsor website must be a valid web address"},400);const sponsorMessageEn=optionalString(body,"sponsorMessageEn",existing.sponsor_message_en,1000),sponsorMessageAr=optionalString(body,"sponsorMessageAr",existing.sponsor_message_ar,1000);await env.DB.prepare(`UPDATE email_template_profiles SET enabled=?, include_islamic_occasion=?, include_daily_hadith=?, include_daily_surah=?, include_occasion_countdown=?, include_motivation=?, include_sadaqah_jariyah=?, include_sponsor=?, sponsor_name=?, sponsor_url=?, sponsor_message_en=?, sponsor_message_ar=?, updated_at=CURRENT_TIMESTAMP WHERE template_key=?`).bind(flag(body.enabled,existing.enabled),flag(body.includeIslamicOccasion,existing.include_islamic_occasion),flag(body.includeDailyHadith,existing.include_daily_hadith),flag(body.includeDailySurah,existing.include_daily_surah),flag(body.includeOccasionCountdown,existing.include_occasion_countdown),flag(body.includeMotivation,existing.include_motivation),flag(body.includeSadaqahJariyah,existing.include_sadaqah_jariyah),flag(body.includeSponsor,existing.include_sponsor),sponsorName,sponsorUrl,sponsorMessageEn,sponsorMessageAr,key).run();await logAdmin(env,adminId,"email_template_profile_updated",key,{fields:Object.keys(body)});return json({ok:true,templateKey:key,sponsor:{name:sponsorName,url:sponsorUrl,messageEn:sponsorMessageEn,messageAr:sponsorMessageAr}})}

async function sendTemplateTest(env:Env,adminId:number,body:Record<string,unknown>){
 const key=clean(body.templateKey,120);if(!key)return json({error:"Template key is required"},400);
 const profile=await env.DB.prepare("SELECT template_key FROM email_template_profiles WHERE template_key = ? LIMIT 1").bind(key).first<{template_key:string}>();if(!profile)return json({error:"Template profile not found"},404);
 const recipient="windsor.hassoun@gmail.com",now=new Date(),dateKey=now.toISOString().slice(0,10),kind=key==="prayer_alert"?"prayer":key,idempotencyKey=`admin-template-test:${key}:${now.toISOString()}`;
 const templateData={kind:"athan",prayer:"isha",prayerLabel:"Isha",prayerTime:"21:48",prayerDate:dateKey,prayerTimes:{fajr:"05:12",dhuhr:"13:35",asr:"17:23",maghrib:"20:26",isha:"21:48"},locationLabel:"Windsor, Ontario",timezone:"America/Toronto",message:`This is a Hassoun test of the ${key} email template.`,verificationUrl:"https://admin.hassoun.app/admin/email",manageUrl:"https://admin.hassoun.app/admin/email",resetUrl:"https://admin.hassoun.app/admin/email",upcomingEvent:{emoji:"🌙",daysLeft:18,nameEn:"Upcoming Islamic Occasion",nameAr:"المناسبة الإسلامية القادمة",descriptionEn:"Prepare with worship, gratitude, family and good deeds.",descriptionAr:"استعد بالعبادة والشكر والأسرة والأعمال الصالحة."}};
 await env.DB.prepare(`INSERT INTO email_outbox (delivery_id,subscriber_id,recipient_email,locale,kind,template_key,template_data_json,idempotency_key,scheduled_at,status) VALUES (NULL,NULL,?,'en',?,NULL,?,?,CURRENT_TIMESTAMP,'pending')`).bind(recipient,kind,JSON.stringify(templateData),idempotencyKey).run();
 const result=await processEmailOutbox(env);await logAdmin(env,adminId,"email_template_test_sent",key,{recipient,result});return json({ok:true,recipient,templateKey:key,...result});
}

async function updateContentItem(env:Env,body:Record<string,unknown>){const id=Number(body.id);if(!Number.isInteger(id)||id<=0)return json({error:"Valid content id is required"},400);const existing=await env.DB.prepare("SELECT id, enabled FROM email_content_library WHERE id = ? LIMIT 1").bind(id).first<{id:number;enabled:number}>();if(!existing)return json({error:"Content item not found"},404);await env.DB.prepare(`UPDATE email_content_library SET title_en=COALESCE(?,title_en), title_ar=COALESCE(?,title_ar), body_en=COALESCE(?,body_en), body_ar=COALESCE(?,body_ar), source_ref=COALESCE(?,source_ref), enabled=?, updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(clean(body.titleEn,180),clean(body.titleAr,180),clean(body.bodyEn,3000),clean(body.bodyAr,3000),clean(body.sourceRef,300),flag(body.enabled,existing.enabled),id).run();return json({ok:true,id})}

export async function createAdminEmailCampaign(request:Request,env:Env){const auth=await requireAdmin(request,env);if(!auth.admin)return auth.response!;const body=await bodyJson(request);if(body.action==="update_template_profile")return updateTemplateProfile(env,auth.admin.id,body);if(body.action==="send_template_test")return sendTemplateTest(env,auth.admin.id,body);if(body.action==="update_content_item")return updateContentItem(env,body);const subjectEn=clean(body.subjectEn,180),htmlEn=clean(body.htmlEn,50000),textEn=clean(body.textEn,20000)||(typeof body.htmlEn==="string"?body.htmlEn.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,20000):null);if(!subjectEn||!htmlEn)return json({error:"English subject and HTML message are required"},400);const campaignCategory=category(body.category),publicId=crypto.randomUUID(),templateKey=`campaign_${publicId.replace(/-/g,"")}`,when=scheduleTime(body.scheduledAt);if(!when)return json({error:"Invalid scheduled time"},400);const subjectAr=clean(body.subjectAr,180),htmlAr=clean(body.htmlAr,50000),textAr=clean(body.textAr,20000),name=clean(body.name,120)||subjectEn,campaignAudience=audience(body.audience),locale=targetLocale(body.targetLocale),countryCode=typeof body.targetCountryCode==="string"&&/^[A-Za-z]{2}$/.test(body.targetCountryCode.trim())?body.targetCountryCode.trim().toUpperCase():null,city=clean(body.targetCity,100),timezone=clean(body.targetTimezone,80);await env.DB.batch([env.DB.prepare(`INSERT INTO email_templates (template_key,name,category,subject_en,subject_ar,html_en,html_ar,text_en,text_ar,enabled) VALUES (?,?,?,?,?,?,?,?,?,1)`).bind(templateKey,name,campaignCategory,subjectEn,subjectAr,htmlEn,htmlAr,textEn,textAr),env.DB.prepare(`INSERT INTO email_campaigns (public_id,name,template_key,category,audience,target_locale,target_country_code,target_city,target_timezone,status,scheduled_at,created_by_admin_id) VALUES (?,?,?,?,?,?,?,?,?,'scheduled',?,?)`).bind(publicId,name,templateKey,campaignCategory,campaignAudience,locale,countryCode,city,timezone,when,auth.admin.id)]);await logAdmin(env,auth.admin.id,"email_campaign_created",publicId,{scheduledAt:when,category:campaignCategory,audience:campaignAudience,locale,countryCode,city,timezone});return json({ok:true,publicId,status:"scheduled",scheduledAt:when},201)}

export async function listAdminEmailCampaigns(request:Request,env:Env){const auth=await requireAdmin(request,env);if(!auth.admin)return auth.response!;const [{results:campaigns},{results:profiles},{results:customTemplates},{results:content}]=await Promise.all([env.DB.prepare(`SELECT c.public_id,c.name,c.category,c.audience,c.target_locale,c.target_country_code,c.target_city,c.target_timezone,c.status,c.scheduled_at,c.started_at,c.sent_at,c.created_at,t.subject_en,t.subject_ar,SUM(CASE WHEN d.status='sent' THEN 1 ELSE 0 END) AS sent_count,SUM(CASE WHEN d.status='failed' THEN 1 ELSE 0 END) AS failed_count,SUM(CASE WHEN d.status='pending' THEN 1 ELSE 0 END) AS pending_count,COUNT(d.id) AS delivery_count FROM email_campaigns c LEFT JOIN email_templates t ON t.template_key=c.template_key LEFT JOIN email_deliveries d ON d.campaign_id=c.id GROUP BY c.id ORDER BY c.id DESC LIMIT 100`).all<Record<string,unknown>>(),env.DB.prepare(`SELECT template_key,name,category,enabled,include_islamic_occasion,include_daily_hadith,include_daily_surah,include_occasion_countdown,include_motivation,include_sadaqah_jariyah,include_sponsor,sponsor_name,sponsor_url,sponsor_message_en,sponsor_message_ar,updated_at FROM email_template_profiles ORDER BY category,name`).all<Record<string,unknown>>(),env.DB.prepare(`SELECT template_key,name,category,subject_en,subject_ar,enabled,updated_at FROM email_templates ORDER BY id DESC LIMIT 200`).all<Record<string,unknown>>(),env.DB.prepare(`SELECT id,content_type,title_en,title_ar,body_en,body_ar,source_ref,enabled,sort_order FROM email_content_library ORDER BY content_type,sort_order,id`).all<Record<string,unknown>>()]);return json({ok:true,campaigns,profiles,customTemplates,content})}
async function subscribers(env:Env){const{results}=await env.DB.prepare(`SELECT s.id,s.public_id,s.email,s.locale,s.country_code,s.country_name,s.region,s.city,s.timezone,p.religious_occasions,p.daily_content,p.announcements,p.community_events,p.marketing FROM email_subscribers s JOIN subscriber_email_preferences p ON p.subscriber_id=s.id WHERE s.status='active'`).all<SubscriberRow>();return results}
async function claimCampaignDelivery(env:Env,c:CampaignRow,s:SubscriberRow){const eventId=`campaign:${c.id}:${s.id}`;const inserted=await env.DB.prepare(`INSERT OR IGNORE INTO email_deliveries (event_id,campaign_id,subscriber_id,recipient_email,template_key,status,notification_kind,scheduled_for) VALUES (?,?,?,?,?,'pending','campaign',?)`).bind(eventId,c.id,s.id,s.email,c.template_key,c.scheduled_at||new Date().toISOString()).run();if((inserted.meta.changes??0)!==1)return null;return env.DB.prepare("SELECT id FROM email_deliveries WHERE event_id=? AND subscriber_id=? LIMIT 1").bind(eventId,s.id).first<{id:number}>()}
async function enqueueCampaign(env:Env,c:CampaignRow){const candidates=(await subscribers(env)).filter(s=>matchesTarget(s,c));let queued=0;for(const s of candidates){const delivery=await claimCampaignDelivery(env,c,s);if(!delivery)continue;const manageUrl=await subscriberManageUrl(env,s.public_id,s.email),idempotencyKey=`email-campaign:${c.id}:${s.id}`;await env.DB.prepare(`INSERT OR IGNORE INTO email_outbox (delivery_id,subscriber_id,recipient_email,locale,kind,template_key,template_data_json,idempotency_key) VALUES (?,?,?,?,?,?,?,?)`).bind(delivery.id,s.id,s.email,s.locale,outboxKind(c.category),c.template_key,JSON.stringify({manageUrl,locationLabel:[s.city,s.region,s.country_name].filter(Boolean).join(", "),timezone:s.timezone,campaignId:c.public_id}),idempotencyKey).run();queued++}return queued}
export async function dispatchDueAdminEmailCampaigns(env:Env){const{results}=await env.DB.prepare(`SELECT id,public_id,name,template_key,category,audience,target_locale,target_country_code,target_city,target_timezone,status,scheduled_at FROM email_campaigns WHERE status='scheduled' AND scheduled_at<=CURRENT_TIMESTAMP ORDER BY scheduled_at,id LIMIT 10`).all<CampaignRow>();for(const c of results){const claimed=await env.DB.prepare(`UPDATE email_campaigns SET status='sending',started_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='scheduled'`).bind(c.id).run();if((claimed.meta.changes??0)!==1)continue;try{const queued=await enqueueCampaign(env,c);if(queued===0)await env.DB.prepare(`UPDATE email_campaigns SET status='sent',sent_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(c.id).run()}catch(error){console.error("Admin email campaign queue failed",{campaignId:c.public_id,error});await env.DB.prepare(`UPDATE email_campaigns SET status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(c.id).run()}}return{processed:results.length}}
export async function refreshAdminEmailCampaignStatuses(env:Env){const{results}=await env.DB.prepare(`SELECT id FROM email_campaigns WHERE status='sending' LIMIT 50`).all<{id:number}>();for(const c of results){const counts=await env.DB.prepare(`SELECT COUNT(*) AS total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) AS pending,SUM(CASE WHEN status='sent' THEN 1 ELSE 0 END) AS sent,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) AS failed FROM email_deliveries WHERE campaign_id=?`).bind(c.id).first<{total:number;pending:number;sent:number;failed:number}>();if(!counts||counts.total===0||(counts.pending??0)>0)continue;const finalStatus=(counts.sent??0)>0?"sent":"failed";await env.DB.prepare(`UPDATE email_campaigns SET status=?,sent_at=CASE WHEN ?='sent' THEN CURRENT_TIMESTAMP ELSE sent_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(finalStatus,finalStatus,c.id).run()}}
