import { requireAdmin } from "./adminAuth";
import { listAdminSubscribers } from "./adminData";
import { listAppSettings, listAuditLog, updateAppSetting, updateSubscriberStatus } from "./adminCrm";
import { createAdminEmailCampaign, listAdminEmailCampaigns } from "./adminEmail";
import { createAdminPushCampaign, dispatchDueAdminPushCampaigns, listAdminPushCampaigns } from "./adminPush";
import { processEmailOutbox } from "./emailDelivery";
import { subscribeByEmail } from "./subscribers";
import type { Env } from "./types";
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}})}
async function authenticated(request:Request,env:Env){const auth=await requireAdmin(request,env);if(!auth.admin)return {admin:null,response:auth.response!};return {admin:auth.admin,response:null}}
async function requireOperator(request:Request,env:Env){const auth=await authenticated(request,env);if(!auth.admin)return auth;if(auth.admin.role!=="owner"&&auth.admin.role!=="admin")return {admin:null,response:json({error:"Owner or admin access required"},403)};return auth}
const isOperator=(role:string)=>role==="owner"||role==="admin";
const ADMIN_TEST_EMAIL="windsor.hassoun@gmail.com";
export async function listRestrictedSubscribers(request:Request,env:Env,url:URL){const auth=await authenticated(request,env);if(!auth.admin)return auth.response!;if(!isOperator(auth.admin.role))return json({ok:true,subscribers:[]});return listAdminSubscribers(request,env,url)}
async function createRestrictedSubscriber(request:Request,env:Env){const auth=await requireOperator(request,env);if(!auth.admin)return auth.response!;const clone=request.clone();const body=await clone.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return json({error:"Invalid request body"},400);const email=typeof body.email==="string"?body.email.trim().toLowerCase():"";if(!email)return json({error:"Email is required"},400);const signup=await subscribeByEmail(request,env);if(!signup.ok)return signup;const row=await env.DB.prepare("SELECT id,public_id,email FROM email_subscribers WHERE email=? COLLATE NOCASE LIMIT 1").bind(email).first<{id:number;public_id:string;email:string}>();if(!row)return json({error:"Subscriber creation failed"},500);await env.DB.batch([env.DB.prepare("UPDATE email_subscribers SET status='active',unsubscribed_at=NULL,verification_token_hash=NULL,verification_expires_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id),env.DB.prepare("UPDATE email_outbox SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE subscriber_id=? AND kind='verification' AND status='pending'").bind(row.id)]);return json({ok:true,subscriber:{public_id:row.public_id,email:row.email,status:"active"}})}
async function sendRestrictedTemplateTest(env:Env,templateKey:string){const profile=await env.DB.prepare("SELECT template_key,name FROM email_template_profiles WHERE template_key=? LIMIT 1").bind(templateKey).first<{template_key:string;name:string}>();if(!profile)return json({error:"Template profile not found"},404);const kind=templateKey==="prayer_alert"?"prayer":templateKey;const testData={message:`This is a Hassoun test email for ${profile.name}.`,verificationUrl:"https://hassoun.app/",manageUrl:"https://hassoun.app/",resetUrl:"https://hassoun.app/admin/",prayer:"fajr",prayerTime:"5:30 AM",locationLabel:"Windsor, Ontario",timezone:"America/Toronto",prayerTimes:{fajr:"5:30 AM",dhuhr:"1:30 PM",asr:"5:00 PM",maghrib:"7:45 PM",isha:"9:00 PM"},upcomingEvent:{emoji:"🌙",nameEn:"Test Islamic Occasion",nameAr:"مناسبة إسلامية تجريبية",descriptionEn:"Test preview of the Islamic occasion section.",descriptionAr:"معاينة تجريبية لقسم المناسبة الإسلامية.",daysLeft:7}};await env.DB.prepare("INSERT INTO email_outbox (recipient_email,locale,kind,template_key,template_data_json,idempotency_key,scheduled_at) VALUES (?,'en',?,?,?,?,CURRENT_TIMESTAMP)").bind(ADMIN_TEST_EMAIL,kind,templateKey,JSON.stringify(testData),`admin-template-test:${templateKey}:${crypto.randomUUID()}`).run();const delivery=await processEmailOutbox(env);return json({ok:true,recipient:ADMIN_TEST_EMAIL,templateKey,delivery})}
export async function listRestrictedAppSettings(request:Request,env:Env){const auth=await authenticated(request,env);if(!auth.admin)return auth.response!;if(!isOperator(auth.admin.role))return json({ok:true,settings:[]});return listAppSettings(request,env)}
export async function updateRestrictedAppSetting(request:Request,env:Env,key:string){const auth=await requireOperator(request,env);if(!auth.admin)return auth.response!;return updateAppSetting(request,env,key)}
export async function updateRestrictedSubscriberStatus(request:Request,env:Env,publicId:string|undefined){const auth=await requireOperator(request,env);if(!auth.admin)return auth.response!;if(!publicId)return json({error:"Subscriber id is required"},400);if(publicId==="create")return createRestrictedSubscriber(request,env);return updateSubscriberStatus(request,env,publicId)}
export async function listRestrictedAuditLog(request:Request,env:Env,url:URL){const auth=await authenticated(request,env);if(!auth.admin)return auth.response!;if(!isOperator(auth.admin.role))return json({ok:true,entries:[]});return listAuditLog(request,env,url)}
export async function createRestrictedPushCampaign(request:Request,env:Env){const auth=await requireOperator(request,env);if(!auth.admin)return auth.response!;const response=await createAdminPushCampaign(request,env);if(response.ok)await dispatchDueAdminPushCampaigns(env);return response}
export async function listRestrictedPushCampaigns(request:Request,env:Env){const auth=await authenticated(request,env);if(!auth.admin)return auth.response!;if(!isOperator(auth.admin.role))return json({ok:true,campaigns:[]});return listAdminPushCampaigns(request,env)}
export async function createRestrictedEmailCampaign(request:Request,env:Env){const auth=await requireOperator(request,env);if(!auth.admin)return auth.response!;const clone=request.clone();const body=await clone.json().catch(()=>null) as Record<string,unknown>|null;if(body?.action==="send_template_test"){const templateKey=typeof body.templateKey==="string"?body.templateKey.trim():"";if(!templateKey)return json({error:"Template key is required"},400);return sendRestrictedTemplateTest(env,templateKey)}return createAdminEmailCampaign(request,env)}
export async function listRestrictedEmailCampaigns(request:Request,env:Env){const auth=await authenticated(request,env);if(!auth.admin)return auth.response!;if(!isOperator(auth.admin.role))return json({ok:true,campaigns:[]});return listAdminEmailCampaigns(request,env)}
