import { prayerDashboardEmail } from "./prayerEmailTemplate";
import type { Env, Locale } from "./types";

type OutboxRow = { id:number; delivery_id:number|null; subscriber_id:number|null; recipient_email:string; locale:Locale; kind:string; template_key:string|null; template_data_json:string|null; idempotency_key:string|null; attempts:number };
type TemplateRow = { subject_en:string; subject_ar:string|null; html_en:string; html_ar:string|null; text_en:string|null; text_ar:string|null };
type RenderedEmail = { subject:string; html:string; text:string };
type ProfileRow = { template_key:string; enabled:number; include_islamic_occasion:number; include_daily_hadith:number; include_daily_surah:number; include_occasion_countdown:number; include_motivation:number; include_sadaqah_jariyah:number; include_sponsor:number; sponsor_name:string|null; sponsor_url:string|null; sponsor_message_en:string|null; sponsor_message_ar:string|null; has_sponsor_logo:number };
type ContentRow = { content_type:"hadith"|"surah"|"motivation"; title_en:string; title_ar:string|null; body_en:string; body_ar:string|null; source_ref:string|null };

function configured(env:Env){return Boolean(env.RESEND_API_KEY&&env.EMAIL_FROM)}
export function emailDeliveryConfigured(env:Env){return configured(env)}
function escapeHtml(value:unknown){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function dataObject(value:string|null){if(!value)return{} as Record<string,unknown>;try{const parsed=JSON.parse(value) as unknown;return parsed&&typeof parsed==="object"?parsed as Record<string,unknown>:{} }catch{return{}}}
function decorateSubject(subject:string){return/[🕌🌙🤲📖✨🔔⏰⏳]/u.test(subject)?subject:`🕌🌙 ${subject} 🤲✨`}

function bilingualShell(options:{eyebrow:string;titleEn:string;titleAr:string;introEn:string;introAr:string;buttonLabelEn?:string;buttonLabelAr?:string;buttonUrl?:string;details?:Array<{labelEn:string;labelAr:string;value:string}>}){
 const details=(options.details??[]).filter(x=>x.value).map(x=>`<tr><td style="padding:7px 0;color:#927437;font-size:10px;font-weight:900;width:130px">${escapeHtml(x.labelEn)}<div dir="rtl" style="color:#a58c55;margin-top:2px">${escapeHtml(x.labelAr)}</div></td><td style="padding:7px 0;color:#173f35;font-size:12px;font-weight:800">${escapeHtml(x.value)}</td></tr>`).join("");
 const action=options.buttonUrl?`<tr><td class="edge" style="padding:0 18px 18px"><a href="${escapeHtml(options.buttonUrl)}" style="display:block;background:#08735a;color:#fff;text-decoration:none;text-align:center;padding:13px;border-radius:12px;font-size:13px;font-weight:900">${escapeHtml(options.buttonLabelEn||"Open Hassoun")}<span style="padding:0 5px">•</span><span dir="rtl">${escapeHtml(options.buttonLabelAr||"فتح Hassoun")}</span></a></td></tr>`:"";
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:520px){.shell{width:100%!important}.edge{padding-left:10px!important;padding-right:10px!important}}</style></head><body style="margin:0;background:#edf0ee;font-family:Arial,Helvetica,sans-serif;color:#173f35"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf0ee;padding:14px 7px"><tr><td align="center"><table class="shell" role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#fff;border-radius:22px;overflow:hidden;border:1px solid #d9e2de"><tr><td align="center" style="background:#073c31;color:#e7c86d;padding:9px;font-size:10px;font-weight:900">✦ ☾ ✦ HASSOUN ✦ ☾ ✦</td></tr><tr><td class="edge" style="padding:22px 20px"><table role="presentation" width="100%"><tr><td width="56"><img src="https://admin.hassoun.app/hassoun-logo.png" width="52" height="52" alt="Hassoun" style="display:block;border-radius:14px;background:#063b31"></td><td style="padding-left:12px"><div style="font-size:10px;letter-spacing:1.6px;color:#a77e29;font-weight:900">${escapeHtml(options.eyebrow)}</div><h1 style="margin:5px 0 2px;font-size:23px;line-height:1.2;color:#143f35">${escapeHtml(options.titleEn)}</h1><div dir="rtl" style="font-size:19px;font-weight:900;color:#8c6b28;margin-top:4px">${escapeHtml(options.titleAr)}</div></td></tr></table><div style="font-size:13px;line-height:1.6;color:#667871;margin-top:14px">${escapeHtml(options.introEn)}</div><div dir="rtl" style="font-size:14px;line-height:1.8;color:#4d665e;margin-top:7px">${escapeHtml(options.introAr)}</div>${details?`<table role="presentation" width="100%" style="margin-top:17px;background:#f7f3e8;border:1px solid #e7dcc2;border-radius:13px;padding:8px 12px">${details}</table>`:""}</td></tr><!--HASSOUN_ENHANCEMENTS-->${action}<tr><td style="background:#0a3028;color:#dfeee9;text-align:center;padding:17px 12px;font-size:10px;line-height:1.7"><strong style="color:#e7cb76">☾ ✦ 🕌 HASSOUN ✦ ☾</strong><br>Prayer • Qur’an • Knowledge • Community<br><span dir="rtl">الصلاة • القرآن • المعرفة • المجتمع</span></td></tr></table></td></tr></table></body></html>`;
}

function builtInSystemEmail(kind:string,data:Record<string,unknown>,_locale:Locale):RenderedEmail{
 if(kind==="verification"){
  const url=String(data.verificationUrl??""),location=String(data.locationLabel??""),timezone=String(data.timezone??"");
  const subject="🕌📧 Confirm your Hassoun prayer email alerts • تأكيد تنبيهات الصلاة 🤲✨";
  return{subject,text:`${subject}\n${url}`,html:bilingualShell({eyebrow:"🕌 HASSOUN",titleEn:"Confirm your prayer email alerts",titleAr:"أكد تنبيهات الصلاة",introEn:"Confirm your email to activate local prayer alerts.",introAr:"أكد بريدك لتفعيل تنبيهات الصلاة حسب موقعك.",details:[{labelEn:"Prayer location",labelAr:"موقع الصلاة",value:location},{labelEn:"Time zone",labelAr:"المنطقة الزمنية",value:timezone}],buttonLabelEn:"Confirm email alerts",buttonLabelAr:"تأكيد التنبيهات",buttonUrl:url})}
 }
 if(kind==="manage"){
  const url=String(data.manageUrl??"");const subject="🕌⚙️ Manage your Hassoun email alerts • إدارة تنبيهات Hassoun 🔔🌙";
  return{subject,text:`${subject}\n${url}`,html:bilingualShell({eyebrow:"⚙️ HASSOUN",titleEn:"Manage your prayer alerts",titleAr:"إدارة تنبيهات الصلاة",introEn:"Change reminder timing, prayer location, or unsubscribe.",introAr:"عدّل أوقات التنبيه أو موقع الصلاة أو ألغِ الاشتراك.",buttonLabelEn:"Open alert settings",buttonLabelAr:"فتح إعدادات التنبيه",buttonUrl:url})}
 }
 if(kind==="admin_password_reset"){
  const url=String(data.resetUrl??"");const subject="🔐🕌 Reset your Hassoun admin password • إعادة تعيين كلمة المرور ✨";
  return{subject,text:`${subject}\n${url}`,html:bilingualShell({eyebrow:"HASSOUN ADMIN",titleEn:"Reset your admin password",titleAr:"إعادة تعيين كلمة المرور",introEn:"Use this secure link to create a new admin password.",introAr:"استخدم هذا الرابط الآمن لإنشاء كلمة مرور جديدة.",buttonLabelEn:"Reset password",buttonLabelAr:"إعادة تعيين كلمة المرور",buttonUrl:url})}
 }
 const message=String(data.message??"Hassoun notification"),subject="🕌🌙 Hassoun notification • تنبيه من Hassoun 🤲✨";
 return{subject,text:`${subject}\n${message}`,html:bilingualShell({eyebrow:"HASSOUN",titleEn:"New notification",titleAr:"تنبيه جديد",introEn:message,introAr:message})}
}

function templateValues(rendered:RenderedEmail,data:Record<string,unknown>){return{...data,emailSubject:rendered.subject,emailHtml:rendered.html,emailText:rendered.text} as Record<string,unknown>}
function applyTemplate(template:string,values:Record<string,unknown>,html:boolean){return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g,(_m,key:string)=>{const value=values[key]??"";return html&&key!=="emailHtml"?escapeHtml(value):String(value)})}
function profileKey(row:OutboxRow){if(row.kind==="prayer")return"prayer_alert";if(["verification","manage","admin_password_reset","religious_occasion","daily_content","announcement","community_event","marketing"].includes(row.kind))return row.kind;return"announcement"}
async function loadProfile(env:Env,row:OutboxRow){return env.DB.prepare(`SELECT template_key,enabled,include_islamic_occasion,include_daily_hadith,include_daily_surah,include_occasion_countdown,include_motivation,include_sadaqah_jariyah,include_sponsor,sponsor_name,sponsor_url,sponsor_message_en,sponsor_message_ar,CASE WHEN sponsor_logo_base64 IS NOT NULL AND sponsor_logo_base64 <> '' THEN 1 ELSE 0 END AS has_sponsor_logo FROM email_template_profiles WHERE template_key=? LIMIT 1`).bind(profileKey(row)).first<ProfileRow>()}
async function loadContent(env:Env){const{results}=await env.DB.prepare(`SELECT content_type,title_en,title_ar,body_en,body_ar,source_ref FROM email_content_library WHERE enabled=1 ORDER BY sort_order,id`).all<ContentRow>();const map=new Map<string,ContentRow>();for(const item of results)if(!map.has(item.content_type))map.set(item.content_type,item);return map}

function bilingualContentRow(item:ContentRow,kind:"quran"|"hadith"|"motivation"){
 const theme=kind==="quran"?{bg:"#eef9f4",border:"#b9dfcf",accent:"#08735a",icon:"📖",label:"QUR’AN • القرآن"}:kind==="hadith"?{bg:"#fff9ec",border:"#ecd28b",accent:"#b07013",icon:"📜",label:"HADITH • الحديث"}:{bg:"#f5f1fb",border:"#d8caed",accent:"#72549a",icon:"🤲",label:"REMINDER • تذكير"};
 return `<tr><td class="edge" style="padding:0 14px 11px"><table role="presentation" width="100%" style="background:${theme.bg};border:1px solid ${theme.border};border-radius:15px"><tr><td style="padding:14px"><div style="font-size:9px;letter-spacing:1.25px;color:${theme.accent};font-weight:900">${theme.icon} ${theme.label}</div><div style="font-size:13px;color:${theme.accent};font-weight:900;margin-top:8px">${escapeHtml(item.title_en)}</div><div style="font-size:14px;line-height:1.65;color:#284d43;font-weight:700;margin-top:5px">${escapeHtml(item.body_en)}</div>${item.title_ar||item.body_ar?`<div dir="rtl" style="border-top:1px solid ${theme.border};margin-top:10px;padding-top:9px;text-align:right"><div style="font-size:13px;color:${theme.accent};font-weight:900">${escapeHtml(item.title_ar||item.title_en)}</div><div style="font-size:15px;line-height:1.8;color:#284d43;font-weight:700;margin-top:4px">${escapeHtml(item.body_ar||item.body_en)}</div></div>`:""}${item.source_ref?`<div style="font-size:10px;color:${theme.accent};font-weight:800;margin-top:8px">✓ ${escapeHtml(item.source_ref)}</div>`:""}</td></tr></table></td></tr>`;
}

function enhancementRows(profile:ProfileRow,content:Map<string,ContentRow>,data:Record<string,unknown>){
 const rows:string[]=[];
 const event=data.upcomingEvent&&typeof data.upcomingEvent==="object"?data.upcomingEvent as Record<string,unknown>:null;
 if(event&&(profile.include_islamic_occasion===1||profile.include_occasion_countdown===1)){
  const nameEn=String(event.nameEn??event.nameAr??""),nameAr=String(event.nameAr??event.nameEn??""),descEn=String(event.descriptionEn??event.descriptionAr??""),descAr=String(event.descriptionAr??event.descriptionEn??""),days=Number(event.daysLeft??0);
  rows.push(`<tr><td class="edge" style="padding:0 14px 11px"><table role="presentation" width="100%" style="background:linear-gradient(135deg,#e9fbf2,#fff9e7);border:1px solid #77c5a8;border-radius:16px"><tr><td align="center" style="padding:15px"><div style="font-size:9px;letter-spacing:1.3px;color:#08735a;font-weight:900">🕌 NEXT ISLAMIC OCCASION • المناسبة الإسلامية القادمة</div>${profile.include_islamic_occasion===1?`<div style="font-size:19px;font-weight:900;color:#08735a;margin-top:7px">${escapeHtml(event.emoji||"🌙")} ${escapeHtml(nameEn)}</div><div dir="rtl" style="font-size:16px;font-weight:900;color:#08735a;margin-top:3px">${escapeHtml(nameAr)}</div><div style="font-size:12px;line-height:1.5;color:#63766f;margin-top:6px">${escapeHtml(descEn)}</div><div dir="rtl" style="font-size:13px;line-height:1.7;color:#63766f;margin-top:4px">${escapeHtml(descAr)}</div>`:""}${profile.include_occasion_countdown===1?`<div style="margin:11px auto 0;background:#fff;border-radius:12px;padding:9px 12px;max-width:220px"><div style="font-size:30px;line-height:1;color:#08735a;font-weight:950">${days}</div><div style="font-size:9px;color:#73847e;margin-top:4px">days remaining • يوم متبقي</div></div>`:""}</td></tr></table></td></tr>`)
 }
 if(profile.include_daily_surah===1&&content.get("surah"))rows.push(bilingualContentRow(content.get("surah")!,"quran"));
 if(profile.include_daily_hadith===1&&content.get("hadith"))rows.push(bilingualContentRow(content.get("hadith")!,"hadith"));
 if(profile.include_motivation===1&&content.get("motivation"))rows.push(bilingualContentRow(content.get("motivation")!,"motivation"));
 if(profile.include_sadaqah_jariyah===1)rows.push(`<tr><td class="edge" style="padding:0 14px 11px"><table role="presentation" width="100%" style="background:#fff2bf;border:1px solid #e9bd42;border-radius:15px"><tr><td align="center" style="padding:14px"><div style="font-size:10px;color:#9a6713;font-weight:900">🌿 CONTINUING SADAQAH JARIYAH • صدقة جارية</div><div style="font-size:13px;line-height:1.6;color:#604d20;font-weight:800;margin-top:7px">Hassoun is offered as a continuing Sadaqah Jariyah for Abdul Jalil Hassoun and Salwa Hassoun. May Allah accept it and continue its reward through everyone who benefits.</div><div dir="rtl" style="font-size:14px;line-height:1.8;color:#604d20;font-weight:800;margin-top:7px">هذا المشروع صدقة جارية عن عبد الجليل حسون وسلمى حسون. نسأل الله أن يتقبله وينفع به ويستمر أجره.</div></td></tr></table></td></tr>`);
 if(profile.include_sponsor===1){
  const name=profile.sponsor_name||"Community Sponsor",messageEn=profile.sponsor_message_en||"Proudly supporting Hassoun and beneficial Islamic tools for the community.",messageAr=profile.sponsor_message_ar||"بدعم كريم يساعد Hassoun على الاستمرار وخدمة المجتمع.",logo=profile.has_sponsor_logo===1?`<img src="https://wopt-prayer-push.wopt-windsor.workers.dev/email/assets/sponsor-logo/${encodeURIComponent(profile.template_key)}" width="118" alt="${escapeHtml(name)}" style="display:block;max-width:118px;max-height:68px;object-fit:contain;margin:8px auto;border:0">`:"",button=profile.sponsor_url?`<a href="${escapeHtml(profile.sponsor_url)}" style="display:inline-block;margin-top:9px;background:#08735a;color:#fff;text-decoration:none;padding:9px 14px;border-radius:9px;font-size:11px;font-weight:900">Visit sponsor • زيارة الراعي</a>`:"";
  rows.push(`<tr><td class="edge" style="padding:0 14px 13px"><table role="presentation" width="100%" style="background:#f5f7f6;border:1px solid #d6e0dc;border-radius:15px"><tr><td align="center" style="padding:15px"><div style="font-size:8px;letter-spacing:1.5px;color:#82928c;font-weight:900">PROUDLY SPONSORED BY • برعاية</div>${logo}<div style="font-size:17px;color:#173f35;font-weight:900">${escapeHtml(name)}</div><div style="font-size:12px;line-height:1.55;color:#677872;margin-top:6px">${escapeHtml(messageEn)}</div><div dir="rtl" style="font-size:13px;line-height:1.7;color:#677872;margin-top:5px">${escapeHtml(messageAr)}</div>${button}</td></tr></table></td></tr>`)
 }
 return rows.join("");
}

function appendEnhancements(rendered:RenderedEmail,rows:string,profile:ProfileRow,content:Map<string,ContentRow>){
 if(!rows)return rendered;
 const textParts:string[]=[];
 if(profile.include_daily_hadith===1&&content.get("hadith")){const x=content.get("hadith")!;textParts.push(`${x.title_en}: ${x.body_en}${x.body_ar?`\n${x.title_ar||x.title_en}: ${x.body_ar}`:""}`)}
 if(profile.include_daily_surah===1&&content.get("surah")){const x=content.get("surah")!;textParts.push(`${x.title_en}: ${x.body_en}${x.body_ar?`\n${x.title_ar||x.title_en}: ${x.body_ar}`:""}`)}
 if(profile.include_sadaqah_jariyah===1)textParts.push("Hassoun is a continuing Sadaqah Jariyah for Abdul Jalil Hassoun and Salwa Hassoun.\nHassoun صدقة جارية عن عبد الجليل حسون وسلمى حسون.");
 if(profile.include_sponsor===1)textParts.push(`${profile.sponsor_message_en||"Community sponsor support."}\n${profile.sponsor_message_ar||"دعم الراعي المجتمعي."}`);
 const html=rendered.html.includes("<!--HASSOUN_ENHANCEMENTS-->")?rendered.html.replace("<!--HASSOUN_ENHANCEMENTS-->",rows):rendered.html.replace("</body>",`<table role="presentation" width="100%" style="max-width:520px;margin:12px auto">${rows}</table></body>`);
 return{...rendered,html,text:`${rendered.text}${textParts.length?`\n\n${textParts.join("\n\n")}`:""}`};
}

function bilingualCustomTemplate(template:TemplateRow,values:Record<string,unknown>,fallback:RenderedEmail){
 const subjectEn=applyTemplate(template.subject_en,values,false),subjectAr=template.subject_ar?applyTemplate(template.subject_ar,values,false):"";
 const htmlEn=applyTemplate(template.html_en,values,true),htmlAr=template.html_ar?applyTemplate(template.html_ar,values,true):"";
 const textEn=template.text_en?applyTemplate(template.text_en,values,false):fallback.text,textAr=template.text_ar?applyTemplate(template.text_ar,values,false):"";
 const subject=subjectAr?`${subjectEn} • ${subjectAr}`:subjectEn;
 const html=htmlAr?`<div dir="ltr">${htmlEn}</div><div dir="rtl" style="margin-top:18px;border-top:1px solid #e6ddd0;padding-top:16px">${htmlAr}</div>`:htmlEn;
 const text=textAr?`${textEn}\n\n${textAr}`:textEn;
 return{subject,html,text};
}

async function renderEmail(env:Env,row:OutboxRow){
 const rawData=dataObject(row.template_data_json),[profile,content]=await Promise.all([loadProfile(env,row),loadContent(env)]);
 let builtIn=row.kind==="prayer"?prayerDashboardEmail(rawData,row.locale):builtInSystemEmail(row.kind,rawData,row.locale);
 if(!["verification","manage","admin_password_reset","prayer"].includes(row.kind)&&row.template_key){
  const template=await env.DB.prepare(`SELECT subject_en,subject_ar,html_en,html_ar,text_en,text_ar FROM email_templates WHERE template_key=? AND enabled=1 LIMIT 1`).bind(row.template_key).first<TemplateRow>();
  if(template)builtIn=bilingualCustomTemplate(template,templateValues(builtIn,rawData),builtIn);
 }
 const forcePreview=rawData.forceTemplatePreview===true;
 if(!profile||(!forcePreview&&profile.enabled!==1))return{...builtIn,subject:decorateSubject(builtIn.subject)};
 const enhanced=appendEnhancements(builtIn,enhancementRows(profile,content,rawData),profile,content);
 return{...enhanced,subject:decorateSubject(enhanced.subject)};
}

async function sendResend(env:Env,row:OutboxRow,email:RenderedEmail){if(!env.RESEND_API_KEY||!env.EMAIL_FROM)throw new Error("Email provider is not configured");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json",...(row.idempotency_key?{"Idempotency-Key":row.idempotency_key.slice(0,256)}:{})},body:JSON.stringify({from:env.EMAIL_FROM.includes("<")?env.EMAIL_FROM.replace(/^[^<]+</,"Hassoun <"):`Hassoun <${env.EMAIL_FROM}>`,to:[row.recipient_email],subject:email.subject,html:email.html,text:email.text,...(env.EMAIL_REPLY_TO?{reply_to:env.EMAIL_REPLY_TO}:{})})});const payload=await response.json().catch(()=>({})) as{id?:string;message?:string;error?:{message?:string}};if(!response.ok||!payload.id)throw new Error(payload.error?.message||payload.message||`Email provider failed: ${response.status}`);return payload.id}
async function claimOutbox(env:Env,id:number){const result=await env.DB.prepare(`UPDATE email_outbox SET status='sending',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(id).run();return(result.meta.changes??0)===1}
async function markSent(env:Env,row:OutboxRow,providerMessageId:string,subject:string){await env.DB.batch([env.DB.prepare(`UPDATE email_outbox SET status='sent',sent_at=CURRENT_TIMESTAMP,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.id),...(row.delivery_id?[env.DB.prepare(`UPDATE email_deliveries SET status='sent',provider_message_id=?,sent_at=CURRENT_TIMESTAMP,subject_snapshot=? WHERE id=?`).bind(providerMessageId,subject,row.delivery_id)]:[])])}
async function markFailure(env:Env,row:OutboxRow,error:unknown){const message=String(error instanceof Error?error.message:error).slice(0,1000),finalFailure=row.attempts+1>=4,statements:D1PreparedStatement[]=[env.DB.prepare(finalFailure?`UPDATE email_outbox SET status='failed',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`:`UPDATE email_outbox SET status='pending',last_error=?,scheduled_at=datetime('now','+5 minutes'),updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(message,row.id)];if(finalFailure&&row.delivery_id)statements.push(env.DB.prepare(`UPDATE email_deliveries SET status='failed',error_message=? WHERE id=?`).bind(message,row.delivery_id));await env.DB.batch(statements)}
export async function processEmailOutbox(env:Env){if(!configured(env))return{configured:false,processed:0,sent:0};const{results}=await env.DB.prepare(`SELECT id,delivery_id,subscriber_id,recipient_email,locale,kind,template_key,template_data_json,idempotency_key,attempts FROM email_outbox WHERE status='pending' AND scheduled_at<=CURRENT_TIMESTAMP AND attempts<4 ORDER BY id LIMIT 25`).all<OutboxRow>();let sent=0;for(const row of results){if(!(await claimOutbox(env,row.id)))continue;try{const email=await renderEmail(env,row),providerMessageId=await sendResend(env,row,email);await markSent(env,row,providerMessageId,email.subject);sent++}catch(error){await markFailure(env,row,error);console.error("Email delivery failed",{outboxId:row.id,error})}}return{configured:true,processed:results.length,sent}}
