import type { Env } from "./types";

type JsonMap = Record<string, unknown>;
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } }); }
async function body(request: Request) { return await request.json() as JsonMap; }
function clean(value: unknown, max = 80) { return typeof value === "string" ? value.trim().replace(/\s+/g, " ").slice(0, max) : ""; }
function validDeviceId(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9_-]{12,80}$/.test(value); }
function validCode(value: unknown): value is string { return typeof value === "string" && /^\d{6}$/.test(value); }
function validSecret(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9_-]{20,160}$/.test(value); }
function randomToken(bytesCount = 24) { const bytes = new Uint8Array(bytesCount); crypto.getRandomValues(bytes); return Array.from(bytes, b => b.toString(16).padStart(2, "0")).join(""); }
function bearer(request: Request) { const value = request.headers.get("Authorization") || ""; const match = /^Bearer\s+([A-Za-z0-9_-]{20,200})$/i.exec(value); return match?.[1] || ""; }
async function controllerAllowed(request: Request, env: Env, deviceId: string) { const token = bearer(request); if (!token) return false; const row = await env.DB.prepare("SELECT id FROM masjid_display_controllers WHERE device_id=? AND controller_token=?").bind(deviceId, token).first(); if (!row) return false; await env.DB.prepare("UPDATE masjid_display_controllers SET last_seen_at=CURRENT_TIMESTAMP WHERE device_id=? AND controller_token=?").bind(deviceId, token).run(); return true; }

const FALLBACK_VERSES = [
  {text:"Indeed, in the remembrance of Allah do hearts find rest.",reference:"Qur’an 13:28",topics:"peace anxiety remembrance heart"},
  {text:"Indeed, Allah is with the patient.",reference:"Qur’an 2:153",topics:"patience hardship difficulty sabr"},
  {text:"So surely with hardship comes ease.",reference:"Qur’an 94:5",topics:"hardship hope ease difficulty"},
  {text:"Whoever relies upon Allah — then He is sufficient for him.",reference:"Qur’an 65:3",topics:"trust tawakkul worry reliance"},
  {text:"Allah does not burden a soul beyond that it can bear.",reference:"Qur’an 2:286",topics:"hardship strength burden hope"},
  {text:"And whatever you spend of good — it will be fully repaid to you.",reference:"Qur’an 2:272",topics:"charity giving donation generosity"},
  {text:"And speak to people good words.",reference:"Qur’an 2:83",topics:"kindness speech community manners"},
  {text:"Indeed, prayer prohibits immorality and wrongdoing.",reference:"Qur’an 29:45",topics:"prayer salah worship guidance"}
];
function fallbackSuggestions(topic:string){const words=topic.toLowerCase().split(/\W+/).filter(Boolean);return [...FALLBACK_VERSES].sort((a,b)=>words.filter(w=>b.topics.includes(w)).length-words.filter(w=>a.topics.includes(w)).length).slice(0,4).map(({text,reference})=>({text,reference}));}

type AiBinding={run:(model:string,input:unknown)=>Promise<unknown>;toMarkdown?:(file:{name:string;blob:Blob},options?:unknown)=>Promise<unknown>};
function aiOf(env:Env){return (env as Env&{AI?:AiBinding}).AI;}
function decodeBase64(value:string){const bin=atob(value);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes;}
function safeJsonArray(raw:string):unknown[]{const cleaned=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/```\s*$/i,"").trim();try{const x=JSON.parse(cleaned);return Array.isArray(x)?x:[]}catch{const a=cleaned.indexOf("[");const b=cleaned.lastIndexOf("]");if(a>=0&&b>a){try{const x=JSON.parse(cleaned.slice(a,b+1));return Array.isArray(x)?x:[]}catch{}}return[]}}
function normalizeDate(v:unknown){const s=clean(v,30);const m=/^(\d{4})[-\/]?(\d{1,2})[-\/]?(\d{1,2})$/.exec(s);if(!m)return"";const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);if(y<2020||y>2100||mo<1||mo>12||d<1||d>31)return"";return`${y}-${String(mo).padStart(2,"0")}-${String(d).padStart(2,"0")}`}
function normalizeTime(v:unknown){let s=clean(v,24).toUpperCase().replace(/\./g,"").replace(/\s+/g," ");if(!s||s==="-"||s==="—")return"";const h12=/^(\d{1,2}):?(\d{2})\s*(AM|PM)$/.exec(s);if(h12){let h=Number(h12[1]);const min=Number(h12[2]);if(h<1||h>12||min>59)return"";return`${h}:${String(min).padStart(2,"0")} ${h12[3]}`;}const h24=/^(\d{1,2}):?(\d{2})$/.exec(s);if(h24){let h=Number(h24[1]),min=Number(h24[2]);if(h>23||min>59)return"";const ap=h>=12?"PM":"AM";h=h%12||12;return`${h}:${String(min).padStart(2,"0")} ${ap}`;}return s.slice(0,20)}
function rowsFromAi(raw:string){const out:Array<Record<string,unknown>>=[];for(const row of safeJsonArray(raw)){if(!Array.isArray(row)||row.length<11)continue;const date=normalizeDate(row[0]);if(!date)continue;out.push({date,fajr:normalizeTime(row[1]),fajrIqama:normalizeTime(row[2]),dhuhr:normalizeTime(row[3]),dhuhrIqama:normalizeTime(row[4]),asr:normalizeTime(row[5]),asrIqama:normalizeTime(row[6]),maghrib:normalizeTime(row[7]),maghribIqama:normalizeTime(row[8]),isha:normalizeTime(row[9]),ishaIqama:normalizeTime(row[10]),confidence:typeof row[11]==="number"?Math.max(0,Math.min(1,row[11])):.8});}return out;}
async function documentText(ai:AiBinding,fileName:string,mimeType:string,bytes:Uint8Array){const lower=fileName.toLowerCase();if(/\.(txt|csv|json)$/i.test(lower)||/^text\//i.test(mimeType)||mimeType==="application/json")return new TextDecoder().decode(bytes);if(!ai.toMarkdown)throw new Error("Document conversion is not available");const converted=await ai.toMarkdown({name:fileName,blob:new Blob([bytes],{type:mimeType||"application/octet-stream"})},{conversionOptions:{output:{format:"markdown"},pdf:{metadata:false}}}) as {data?:string;format?:string;error?:string}|Array<{data?:string;format?:string;error?:string}>;const item=Array.isArray(converted)?converted[0]:converted;if(!item||item.format==="error"||!item.data)throw new Error(item?.error||"Could not extract document text");return item.data;}
async function extractSchedule(ai:AiBinding,text:string){const chunks:string[]=[];const max=16000;for(let i=0;i<text.length&&chunks.length<30;i+=max)chunks.push(text.slice(i,i+max));const map=new Map<string,Record<string,unknown>>();for(let i=0;i<chunks.length;i++){const prompt=`Extract mosque prayer schedule rows from this document chunk. Return ONLY JSON array rows, no markdown. Each row MUST be exactly [date,fajrAdhan,fajrIqama,dhuhrAdhan,dhuhrIqama,asrAdhan,asrIqama,maghribAdhan,maghribIqama,ishaAdhan,ishaIqama,confidence]. Date must be YYYY-MM-DD. Times should preserve AM/PM if shown. Understand synonyms such as Salah/Prayer, Adhan/Azan/Athan, Iqama/Iqamah/Jamaat. The source may be a monthly or yearly mosque calendar. Do not invent missing values: use empty string. If a year/month heading applies to following day numbers, infer the full date only from that heading. confidence is 0 to 1. Ignore Sunrise/Shuruq. Document chunk ${i+1}/${chunks.length}:\n${chunks[i]}`;try{const result=await ai.run("@cf/meta/llama-3.1-8b-instruct",{messages:[{role:"system",content:"You convert mosque prayer timetables into strict structured JSON. Never invent prayer times."},{role:"user",content:prompt}],max_tokens:6500,temperature:.05}) as {response?:string};for(const row of rowsFromAi(String(result?.response||""))){const date=String(row.date);const old=map.get(date);if(!old||Number(row.confidence||0)>Number(old.confidence||0))map.set(date,row);}}catch(error){console.error("Schedule chunk parse failed",i,error)}}return [...map.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,370);}
function scheduleWarnings(rows:Array<Record<string,unknown>>){const warnings:string[]=[];const low=rows.filter(r=>Number(r.confidence||0)<.65).length;if(low)warnings.push(`${low} row${low===1?"":"s"} need review`);if(rows.length<28)warnings.push("Only a partial schedule may have been detected");return warnings;}

export async function handleMasjidDisplays(request: Request, env: Env, url: URL): Promise<Response | null> {
  if (!url.pathname.startsWith("/masjid-displays/")) return null;
  if (request.method === "POST" && url.pathname === "/masjid-displays/ai/verse") {
    const data=await body(request),deviceId=clean(data.deviceId,80),topic=clean(data.topic,240);
    if(!validDeviceId(deviceId)||!(await controllerAllowed(request,env,deviceId)))return json({error:"Not paired"},401);
    if(topic.length<3)return json({error:"Describe the kind of Qur’an message you want"},400);
    const ai=aiOf(env);
    if(ai){try{const prompt=`You help a mosque administrator choose short Qur'an verses for a public prayer-time display. The admin wants a verse about: ${topic}. Return ONLY valid JSON as an array of 4 objects, each with keys text and reference. Use concise, faithful English translations and exact Qur'an references such as Qur’an 2:153. Do not invent verses or references. Prefer verses short enough for a TV header.`;const result=await ai.run("@cf/meta/llama-3.1-8b-instruct",{messages:[{role:"system",content:"Return only JSON. Accuracy of Qur'an references is essential."},{role:"user",content:prompt}],max_tokens:700,temperature:.25}) as {response?:string};const raw=String(result?.response||"").replace(/^```json\s*|```$/g,"").trim();const parsed=JSON.parse(raw) as unknown;if(Array.isArray(parsed)){const options=parsed.map(x=>x&&typeof x==='object'?x as Record<string,unknown>:{}).map(x=>({text:clean(x.text,240),reference:clean(x.reference,50)})).filter(x=>x.text&&/^Qur[’']?an\s+\d{1,3}:\d{1,3}/i.test(x.reference)).slice(0,4);if(options.length>=2)return json({ok:true,source:"ai",options});}}catch(error){console.error("Masjid verse AI failed",error);}}
    return json({ok:true,source:"curated",options:fallbackSuggestions(topic)});
  }
  if(request.method==="POST"&&url.pathname==="/masjid-displays/ai/schedule-import"){
    const data=await body(request),deviceId=clean(data.deviceId,80),fileName=clean(data.fileName,120),mimeType=clean(data.mimeType,120),base64=typeof data.base64==="string"?data.base64:"";
    if(!validDeviceId(deviceId)||!(await controllerAllowed(request,env,deviceId)))return json({error:"Not paired"},401);
    if(!fileName||!base64)return json({error:"Choose a schedule file"},400);
    if(base64.length>26_000_000)return json({error:"File is too large. Keep it under about 18 MB."},413);
    const ai=aiOf(env);if(!ai)return json({error:"Hassoun AI is not available"},503);
    try{const bytes=decodeBase64(base64);const text=await documentText(ai,fileName,mimeType,bytes);if(text.trim().length<20)return json({error:"The file did not contain readable schedule data"},400);const rows=await extractSchedule(ai,text);if(!rows.length)return json({error:"Hassoun could not find dated prayer-time rows. Check that the file contains dates and prayer times."},422);return json({ok:true,rows,warnings:scheduleWarnings(rows),sourceLength:text.length});}catch(error){console.error("Prayer schedule import failed",error);return json({error:error instanceof Error?error.message:"Could not process schedule file"},500)}
  }
  if(request.method==="POST"&&url.pathname==="/masjid-displays/ai/schedule-text"){
    const data=await body(request),deviceId=clean(data.deviceId,80),text=typeof data.text==="string"?data.text.trim():"";
    if(!validDeviceId(deviceId)||!(await controllerAllowed(request,env,deviceId)))return json({error:"Not paired"},401);
    if(text.length<20)return json({error:"Paste the prayer schedule text first"},400);
    if(text.length>400_000)return json({error:"Pasted schedule text is too long"},413);
    const ai=aiOf(env);if(!ai)return json({error:"Hassoun AI is not available"},503);
    try{const rows=await extractSchedule(ai,text);if(!rows.length)return json({error:"Hassoun could not detect dated prayer-time rows in the pasted text. Include the month/year or full dates with the prayer times."},422);return json({ok:true,rows,warnings:scheduleWarnings(rows),sourceLength:text.length});}catch(error){console.error("Prayer pasted-text import failed",error);return json({error:error instanceof Error?error.message:"Could not analyze pasted schedule text"},500)}
  }
  if (request.method === "POST" && url.pathname === "/masjid-displays/register") {
    const data = await body(request);
    if (!validDeviceId(data.deviceId) || !validCode(data.pairCode) || !validSecret(data.deviceSecret)) return json({ error: "Invalid display registration" }, 400);
    const existing = await env.DB.prepare("SELECT device_secret,settings_json,revision FROM masjid_displays WHERE device_id=?").bind(data.deviceId).first<{device_secret:string;settings_json:string;revision:number}>();
    if (existing && existing.device_secret !== data.deviceSecret) return json({ error: "Display secret mismatch" }, 403);
    const name = clean(data.name, 40) || "Masjid Display";
    const settings = data.settings && typeof data.settings === "object" ? JSON.stringify(data.settings) : "{}";
    let revision = 1;
    if (existing) { const changed = existing.settings_json !== settings; revision = existing.revision + (changed ? 1 : 0); await env.DB.prepare("UPDATE masjid_displays SET pair_code=?,name=?,settings_json=?,revision=?,last_seen_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE device_id=?").bind(data.pairCode, name, settings, revision, data.deviceId).run(); }
    else { await env.DB.prepare("INSERT INTO masjid_displays (device_id,pair_code,device_secret,name,settings_json,revision) VALUES (?,?,?,?,?,1)").bind(data.deviceId, data.pairCode, data.deviceSecret, name, settings).run(); }
    return json({ ok: true, deviceId: data.deviceId, pairCode: data.pairCode, name, revision });
  }
  if (request.method === "POST" && url.pathname === "/masjid-displays/pair") {
    const data = await body(request); if (!validCode(data.code)) return json({ error: "Enter the 6-digit code shown on the display" }, 400);
    const display = await env.DB.prepare("SELECT device_id,name,settings_json,revision FROM masjid_displays WHERE pair_code=?").bind(data.code).first<{device_id:string;name:string;settings_json:string;revision:number}>(); if (!display) return json({ error: "Pairing code not found" }, 404);
    const token = randomToken(28); const controllerName = clean(data.controllerName, 50) || "Hassoun Browser"; await env.DB.prepare("INSERT INTO masjid_display_controllers (device_id,controller_token,controller_name) VALUES (?,?,?)").bind(display.device_id, token, controllerName).run(); let settings: unknown = {}; try { settings = JSON.parse(display.settings_json || "{}"); } catch {} return json({ ok: true, deviceId: display.device_id, name: display.name, token, settings, revision: display.revision });
  }
  const deviceMatch = /^\/masjid-displays\/device\/([A-Za-z0-9_-]{12,80})$/.exec(url.pathname);
  if (deviceMatch && request.method === "GET") { const deviceId = deviceMatch[1], secret = url.searchParams.get("secret") || ""; const display = await env.DB.prepare("SELECT device_secret,name,settings_json,revision,pair_code FROM masjid_displays WHERE device_id=?").bind(deviceId).first<{device_secret:string;name:string;settings_json:string;revision:number;pair_code:string}>(); if (!display || display.device_secret !== secret) return json({ error: "Display not found" }, 404); await env.DB.prepare("UPDATE masjid_displays SET last_seen_at=CURRENT_TIMESTAMP WHERE device_id=?").bind(deviceId).run(); let settings: unknown = {}; try { settings = JSON.parse(display.settings_json || "{}"); } catch {} return json({ ok: true, deviceId, name: display.name, settings, revision: display.revision, pairCode: display.pair_code }); }
  const controlMatch = /^\/masjid-displays\/control\/([A-Za-z0-9_-]{12,80})$/.exec(url.pathname);
  if (controlMatch && request.method === "GET") { const deviceId = controlMatch[1]; if (!(await controllerAllowed(request, env, deviceId))) return json({ error: "Not paired" }, 401); const display = await env.DB.prepare("SELECT name,settings_json,revision,last_seen_at FROM masjid_displays WHERE device_id=?").bind(deviceId).first<{name:string;settings_json:string;revision:number;last_seen_at:string}>(); if (!display) return json({ error: "Display not found" }, 404); let settings: unknown = {}; try { settings = JSON.parse(display.settings_json || "{}"); } catch {} return json({ ok: true, deviceId, name: display.name, settings, revision: display.revision, lastSeenAt: display.last_seen_at }); }
  if (controlMatch && request.method === "POST") { const deviceId = controlMatch[1]; if (!(await controllerAllowed(request, env, deviceId))) return json({ error: "Not paired" }, 401); const data = await body(request); const fields: string[] = []; const values: unknown[] = []; if (data.name !== undefined) { fields.push("name=?"); values.push(clean(data.name, 40) || "Masjid Display"); } if (data.settings && typeof data.settings === "object") { fields.push("settings_json=?"); values.push(JSON.stringify(data.settings)); } if (!fields.length) return json({ error: "Nothing to update" }, 400); fields.push("revision=revision+1", "updated_at=CURRENT_TIMESTAMP"); await env.DB.prepare(`UPDATE masjid_displays SET ${fields.join(",")} WHERE device_id=?`).bind(...values, deviceId).run(); const updated = await env.DB.prepare("SELECT revision FROM masjid_displays WHERE device_id=?").bind(deviceId).first<{revision:number}>(); return json({ ok: true, revision: updated?.revision || 0 }); }
  return json({ error: "Not found" }, 404);
}
