import type { Locale, PrayerKey } from "./types";

export type PrayerEmailRendered={subject:string;html:string;text:string};
type PrayerTimes=Partial<Record<PrayerKey,string>>;
const NAMES:Record<PrayerKey,{en:string;ar:string}>={fajr:{en:"Fajr",ar:"الفجر"},dhuhr:{en:"Dhuhr",ar:"الظهر"},asr:{en:"Asr",ar:"العصر"},maghrib:{en:"Maghrib",ar:"المغرب"},isha:{en:"Isha",ar:"العشاء"}};
const PRAYERS:PrayerKey[]=["fajr","dhuhr","asr","maghrib","isha"];
const ICONS:Record<PrayerKey,string>={fajr:"🌅",dhuhr:"☀️",asr:"🌤️",maghrib:"🌇",isha:"🌙"};
function esc(v:unknown){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function time12(v:unknown){const t=String(v??""),m=t.match(/^(\d{1,2}):(\d{2})/);if(!m)return t;const h=Number(m[1]);return`${h%12||12}:${m[2]} ${h>=12?"PM":"AM"}`}
function dateLabel(dateKey:string,locale:Locale,calendar?:string){try{return new Intl.DateTimeFormat(locale==="ar"?(calendar?"ar-u-ca-islamic-umalqura":"ar-CA"):(calendar?"en-u-ca-islamic-umalqura":"en-CA"),{calendar:calendar||undefined,timeZone:"UTC",weekday:calendar?undefined:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date(`${dateKey}T12:00:00Z`))}catch{return calendar?"":dateKey}}

export function prayerDashboardEmail(data:Record<string,unknown>,_locale:Locale):PrayerEmailRendered{
 const key=(typeof data.prayer==="string"&&data.prayer in NAMES?data.prayer:"fajr") as PrayerKey;
 const kind=String(data.kind??"athan"),date=String(data.prayerDate??new Date().toISOString().slice(0,10)),ptime=time12(data.prayerTime),location=String(data.locationLabel??"Windsor, Ontario"),manageUrl=String(data.manageUrl??""),times=(data.prayerTimes&&typeof data.prayerTimes==="object"?data.prayerTimes:{}) as PrayerTimes;
 const enStatus=kind==="twenty"?"20 minutes until prayer":kind==="ten"?"10 minutes until prayer":"Prayer time now";
 const arStatus=kind==="twenty"?"متبقي ٢٠ دقيقة للصلاة":kind==="ten"?"متبقي ١٠ دقائق للصلاة":"وقت الصلاة الآن";
 const enSubject=kind==="twenty"?`🕌⏳ ${NAMES[key].en} in 20 minutes`:kind==="ten"?`🕌⏰ ${NAMES[key].en} in 10 minutes`:`🕌🔔 It’s time for ${NAMES[key].en}`;
 const arSubject=kind==="twenty"?`بقي ٢٠ دقيقة على صلاة ${NAMES[key].ar}`:kind==="ten"?`بقي ١٠ دقائق على صلاة ${NAMES[key].ar}`:`حان وقت صلاة ${NAMES[key].ar}`;
 const subject=`${enSubject} • ${arSubject} 🌙🤲`;
 const currentIndex=PRAYERS.indexOf(key),nextKey=PRAYERS[(currentIndex+1)%PRAYERS.length]??"fajr",nextTime=time12(times[nextKey]);
 const chips=PRAYERS.map(p=>{const active=p===key;return `<td width="20%" style="padding:2px"><table role="presentation" width="100%" style="background:${active?"#08735a":"#f7faf8"};border:1px solid ${active?"#08735a":"#dce7e2"};border-radius:10px"><tr><td align="center" style="padding:8px 2px;color:${active?"#fff":"#31584d"}"><div style="font-size:15px">${ICONS[p]}</div><div style="font-size:9px;font-weight:900;margin-top:3px">${esc(NAMES[p].en)}</div><div dir="rtl" style="font-size:10px;font-weight:800;margin-top:2px;color:${active?"#ffe7a0":"#577269"}">${esc(NAMES[p].ar)}</div><div style="font-size:9px;font-weight:900;color:${active?"#ffe7a0":"#73847e"};margin-top:3px">${esc(time12(times[p]))}</div></td></tr></table></td>`}).join("");
 const manage=manageUrl?`<tr><td class="edge" style="padding:0 14px 13px"><a href="${esc(manageUrl)}" style="display:block;text-align:center;background:#08735a;color:#fff;text-decoration:none;border-radius:11px;padding:12px;font-size:12px;font-weight:900">⚙️ Manage prayer alerts • إدارة تنبيهات الصلاة</a></td></tr>`:"";
 const logo="https://admin.hassoun.app/hassoun-logo.png";
 const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:520px){.shell{width:100%!important}.edge{padding-left:10px!important;padding-right:10px!important}.hero-time{font-size:32px!important}.prayers td{display:inline-block!important;width:20%!important;box-sizing:border-box}}</style></head><body style="margin:0;background:#edf0ee;font-family:Arial,Helvetica,sans-serif;color:#173f35"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf0ee;padding:14px 6px"><tr><td align="center"><table class="shell" role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:520px;background:#fff;border:1px solid #d8e2de;border-radius:22px;overflow:hidden">
 <tr><td style="background:#064d3e;padding:20px 16px 18px;text-align:center;color:white"><img src="${logo}" width="62" height="62" alt="Hassoun" style="display:block;margin:0 auto 8px;border-radius:17px;border:2px solid #d8bd68;background:#063b31"><div style="font-size:10px;letter-spacing:1.7px;color:#e8cc75;font-weight:900">✦ HASSOUN • صلاة • QUR’AN ✦</div><div style="font-size:11px;color:#cce7de;margin-top:7px">${esc(enStatus)}</div><div dir="rtl" style="font-size:12px;color:#f0ddd0;margin-top:3px">${esc(arStatus)}</div><div style="font-size:22px;font-weight:950;margin-top:7px">${ICONS[key]} ${esc(NAMES[key].en)}</div><div dir="rtl" style="font-size:17px;font-weight:900;color:#e9d48c;margin-top:2px">${esc(NAMES[key].ar)}</div><div class="hero-time" style="font-size:38px;color:#ffe18a;font-weight:950;margin-top:7px">${esc(ptime)}</div></td></tr>
 <tr><td style="background:#eaf8f2;border-bottom:1px solid #cfe9de;text-align:center;padding:8px 10px;color:#08735a;font-size:10px;font-weight:800"><div>${esc(dateLabel(date,"en","islamic-umalqura"))}</div><div dir="rtl" style="margin-top:2px">${esc(dateLabel(date,"ar","islamic-umalqura"))}</div></td></tr>
 <tr><td class="edge" style="padding:10px 14px 4px;text-align:center;color:#75847f;font-size:10px">📍 ${esc(location)}<br><span>${esc(dateLabel(date,"en"))}</span><br><span dir="rtl">${esc(dateLabel(date,"ar"))}</span></td></tr>
 <tr><td class="edge" style="padding:7px 14px 9px"><table role="presentation" width="100%" style="background:#f8faf9;border:1px solid #e1e9e6;border-radius:13px"><tr><td style="padding:11px 12px;text-align:left"><div style="font-size:9px;color:#788983;font-weight:800">NEXT PRAYER • الصلاة القادمة</div><div style="font-size:13px;color:#08735a;font-weight:950;margin-top:4px">${ICONS[nextKey]} ${esc(NAMES[nextKey].en)} • ${esc(NAMES[nextKey].ar)} • ${esc(nextTime)}</div></td></tr></table></td></tr>
 <tr><td class="edge" style="padding:0 11px 11px"><table class="prayers" role="presentation" width="100%"><tr>${chips}</tr></table></td></tr>
 <!--HASSOUN_ENHANCEMENTS-->
 ${manage}
 <tr><td style="border-top:1px solid #e1e8e5;text-align:center;padding:14px 12px;color:#74847e;font-size:9px;line-height:1.6"><div style="color:#08735a;font-weight:900">☾ ✦ 🕌 HASSOUN ✦ ☾</div><div style="margin-top:4px">Prayer • Qur’an • Knowledge • Community</div><div dir="rtl">الصلاة • القرآن • المعرفة • المجتمع</div><div style="margin-top:7px">Prayer times follow your selected location. Islamic dates may vary by local moon sighting.</div><div dir="rtl">مواقيت الصلاة حسب موقعك وقد تختلف التواريخ الإسلامية بحسب رؤية الهلال المحلية.</div></td></tr>
 </table></td></tr></table></body></html>`;
 const scheduleText=PRAYERS.map(p=>`${NAMES[p].en}/${NAMES[p].ar} ${time12(times[p])}`).join(" • ");
 const text=`${subject}\n${location}\n${dateLabel(date,"en")}\n${dateLabel(date,"ar")}\n${scheduleText}${manageUrl?`\n\nManage alerts / إدارة التنبيهات: ${manageUrl}`:""}`;
 return{subject,html,text}
}
