import type { Locale, PrayerKey } from "./types";

export type PrayerEmailRendered={subject:string;html:string;text:string};
type PrayerTimes=Partial<Record<PrayerKey,string>>;
type UpcomingEvent={id?:string;emoji?:string;dateKey?:string;daysLeft?:number;nameEn?:string;nameAr?:string;descriptionEn?:string;descriptionAr?:string};
const NAMES:Record<PrayerKey,{en:string;ar:string}>={fajr:{en:"Fajr",ar:"الفجر"},dhuhr:{en:"Dhuhr",ar:"الظهر"},asr:{en:"Asr",ar:"العصر"},maghrib:{en:"Maghrib",ar:"المغرب"},isha:{en:"Isha",ar:"العشاء"}};
const PRAYERS:PrayerKey[]=["fajr","dhuhr","asr","maghrib","isha"];
const ICONS:Record<PrayerKey,string>={fajr:"🌅",dhuhr:"☀️",asr:"🌤️",maghrib:"🌇",isha:"🌙"};
function esc(v:unknown){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function time12(v:unknown){const t=String(v??""),m=t.match(/^(\d{1,2}):(\d{2})/);if(!m)return t;const h=Number(m[1]);return`${h%12||12}:${m[2]} ${h>=12?"PM":"AM"}`}
function dateLabel(dateKey:string,locale:Locale,calendar?:string){try{return new Intl.DateTimeFormat(locale==="ar"?(calendar?"ar-u-ca-islamic-umalqura":"ar-CA"):(calendar?"en-u-ca-islamic-umalqura":"en-CA"),{calendar:calendar||undefined,timeZone:"UTC",weekday:calendar?undefined:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date(`${dateKey}T12:00:00Z`))}catch{return calendar?"":dateKey}}
function prayerName(p:unknown,l:Locale){return typeof p==="string"&&p in NAMES?NAMES[p as PrayerKey][l]:l==="ar"?"الصلاة":"Prayer"}

export function prayerDashboardEmail(data:Record<string,unknown>,locale:Locale):PrayerEmailRendered{
 const ar=locale==="ar",t=(en:string,ara:string)=>ar?ara:en,key=(typeof data.prayer==="string"&&data.prayer in NAMES?data.prayer:"fajr") as PrayerKey,prayer=prayerName(key,locale),kind=String(data.kind??"athan"),date=String(data.prayerDate??new Date().toISOString().slice(0,10)),ptime=time12(data.prayerTime),location=String(data.locationLabel??t("your location","موقعك")),manageUrl=String(data.manageUrl??""),times=(data.prayerTimes&&typeof data.prayerTimes==="object"?data.prayerTimes:{}) as PrayerTimes,event=(data.upcomingEvent&&typeof data.upcomingEvent==="object"?data.upcomingEvent:null) as UpcomingEvent|null;
 const subject=ar?(kind==="twenty"?`🕌⏳ بقي ٢٠ دقيقة على صلاة ${prayer} 🌙🤲`:kind==="ten"?`🕌⏰ بقي ١٠ دقائق على صلاة ${prayer} ✨🤲`:`🕌🔔 حان وقت صلاة ${prayer} 🌙🤲`):(kind==="twenty"?`🕌⏳ ${prayer} in 20 minutes 🌙🤲`:kind==="ten"?`🕌⏰ ${prayer} in 10 minutes ✨🤲`:`🕌🔔 It’s time for ${prayer} 🌙🤲`);
 const kicker=kind==="twenty"?t("20 MINUTES TO PRAYER","متبقي ٢٠ دقيقة"):kind==="ten"?t("10 MINUTES TO PRAYER","متبقي ١٠ دقائق"):t("IT’S PRAYER TIME","حان وقت الصلاة");
 const cards=PRAYERS.map(p=>{const active=p===key;return `<td width="20%" style="padding:3px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${active?"#0b5b47":"#fffdf8"};border:1px solid ${active?"#0b5b47":"#e5ddca"};border-radius:14px"><tr><td align="center" style="padding:10px 3px;color:${active?"#fff":"#173f35"}"><div style="font-size:20px">${ICONS[p]}</div><div style="font-size:11px;font-weight:800;margin-top:4px">${esc(NAMES[p][locale])}</div><div style="font-size:12px;font-weight:900;color:${active?"#f6d87b":"#31584d"};margin-top:4px">${esc(time12(times[p]))}</div></td></tr></table></td>`}).join("");
 const eventBlock=event&&typeof event.daysLeft==="number"&&event.daysLeft<=30?`<tr><td style="padding:0 14px 12px"><table role="presentation" width="100%" style="background:#fff4cf;border:1px solid #dfc268;border-radius:16px"><tr><td dir="${ar?"rtl":"ltr"}" style="padding:15px;text-align:${ar?"right":"left"}"><div style="font-size:10px;letter-spacing:1.4px;color:#8c6a20;font-weight:900">🌙 ✦ ${esc(t("UPCOMING ISLAMIC OCCASION","المناسبة الإسلامية القادمة"))} ✦ 🌙</div><div style="font-size:19px;font-weight:900;color:#173f35;margin-top:6px">${esc(event.emoji||"🌙")} ${esc(ar?event.nameAr||event.nameEn:event.nameEn||event.nameAr)}</div><div style="font-size:13px;line-height:1.55;color:#5f6f69;margin-top:5px">${esc(ar?event.descriptionAr||event.descriptionEn:event.descriptionEn||event.descriptionAr)}</div><div style="display:inline-block;margin-top:10px;background:#0b5b47;color:white;border-radius:99px;padding:7px 11px;font-size:11px;font-weight:900">🕌⏳ ${esc(ar?`متبقي ${event.daysLeft} يوم`:`${event.daysLeft} days remaining`)}</div></td></tr></table></td></tr>`:"";
 const manage=manageUrl?`<tr><td style="padding:2px 14px 16px"><a href="${esc(manageUrl)}" style="display:block;text-align:center;background:#0b5b47;color:#fff;text-decoration:none;border-radius:13px;padding:13px;font-size:13px;font-weight:900">⚙️ ${esc(t("Manage prayer alerts","إدارة تنبيهات الصلاة"))} 🔔</a></td></tr>`:"";
 const direction=ar?"rtl":"ltr",align=ar?"right":"left",logo="https://hassoun.app/hassoun-logo.png";
 const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:520px){.shell{width:100%!important}.pad{padding-left:12px!important;padding-right:12px!important}.hero-title{font-size:28px!important}.schedule td{display:inline-block!important;width:50%!important;box-sizing:border-box}.schedule td:last-child{width:100%!important}.top-location{display:block!important;text-align:${align}!important;padding-top:7px!important}}</style></head><body style="margin:0;background:#eee7d8;font-family:Arial,Helvetica,sans-serif;color:#173f35"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eee7d8;padding:12px 6px"><tr><td align="center"><table class="shell" role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fbf7ec;border:1px solid #d9cba9;border-radius:24px;overflow:hidden" dir="${direction}">
 <tr><td align="center" style="background:#133f35;color:#e9cf84;padding:9px 12px;font-size:11px;font-weight:800">✦ ☾ ✦ ${esc(t("In the name of Allah, the Most Gracious, the Most Merciful","بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ"))} ✦ ☾ ✦</td></tr>
 <tr><td style="background:#0b352c;padding:20px 18px;text-align:center"><img src="${logo}" width="82" height="82" alt="Hassoun" style="display:inline-block;border-radius:20px;border:2px solid #d7b75d;background:#073c32"><div style="font-size:10px;letter-spacing:2px;color:#e5c96e;font-weight:900;margin-top:10px">HASSOUN • صلاة • قرآن</div><div class="hero-title" style="font-size:34px;line-height:1.12;color:white;font-weight:900;margin-top:7px">${ICONS[key]} ${esc(prayer)}</div><div style="font-size:12px;color:#c8ddd6;margin-top:4px">${esc(NAMES[key][ar?"en":"ar"])}</div><div style="font-size:30px;color:#f5d77d;font-weight:900;margin-top:8px">${esc(ptime)}</div><div style="margin:14px auto 0;max-width:500px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.09);border-radius:14px;padding:12px;color:#eff8f5;font-size:13px;line-height:1.55;font-weight:700">🤲 ${esc(t("May Allah accept your prayer, fill your heart with sakinah, and place barakah in your day.","نسأل الله أن يتقبل صلاتك ويملأ قلبك سكينة ويبارك لك في يومك."))}</div></td></tr>
 <tr><td style="background:#fbf7ec;text-align:center;color:#a47d2e;padding:7px">✦ ✦ ✦</td></tr>
 <tr><td class="pad" style="padding:12px 14px 6px"><table role="presentation" width="100%"><tr><td style="text-align:${align}"><div style="font-size:11px;font-weight:900;color:#173f35">🕋 ${esc(t("Today’s prayer schedule","جدول صلوات اليوم"))}</div><div style="font-size:10px;color:#72837d;margin-top:3px">${esc(dateLabel(date,locale))} • ${esc(dateLabel(date,locale,"islamic-umalqura"))}</div></td><td class="top-location" style="text-align:${ar?"left":"right"};font-size:10px;color:#72837d">📍 ${esc(location)}</td></tr></table></td></tr>
 <tr><td class="pad" style="padding:3px 10px 13px"><table class="schedule" role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr>${cards}</tr></table></td></tr>
 <tr><td style="padding:0 14px 12px"><table role="presentation" width="100%" style="background:#edf7f2;border:1px solid #cfe2d9;border-radius:16px"><tr><td dir="${direction}" style="padding:15px;text-align:${align}"><div style="font-size:10px;letter-spacing:1.3px;color:#0b735a;font-weight:900">📖 ✦ ${esc(t("QUR’AN REFLECTION","تدبر قرآني"))} ✦</div><div style="font-size:16px;line-height:1.65;color:#244d42;font-weight:800;margin-top:6px">${esc(t("Surely, in the remembrance of Allah do hearts find comfort.","ألا بذكر الله تطمئن القلوب."))}</div><div style="font-size:10px;color:#71827c;margin-top:5px">Qur’an 13:28</div></td></tr></table></td></tr>
 ${eventBlock}${manage}
 <tr><td style="background:#0a3028;color:#edf7f3;text-align:center;padding:18px 14px"><div style="font-size:13px;color:#e9cf84;font-weight:900">☾ ✦ 🕌 HASSOUN ✦ ☾</div><div style="font-size:10px;margin-top:5px">${esc(t("Prayer • Qur’an • Knowledge • Community","الصلاة • القرآن • المعرفة • المجتمع"))}</div><div style="font-size:9px;color:#a9c0b8;margin-top:8px">${esc(t("Prayer times follow your selected location. Islamic dates may vary by local moon sighting.","مواقيت الصلاة حسب موقعك وقد تختلف التواريخ الإسلامية بحسب رؤية الهلال المحلية."))}</div></td></tr>
 </table></td></tr></table></body></html>`;
 const scheduleText=PRAYERS.map(p=>`${NAMES[p][locale]} ${time12(times[p])}`).join(" • ");const eventText=event&&typeof event.daysLeft==="number"?`\n${ar?event.nameAr||event.nameEn:event.nameEn||event.nameAr}: ${event.daysLeft} ${t("days remaining","يوم متبقي")}`:"";const text=`${subject}\n${location}\n${dateLabel(date,locale)}\n${scheduleText}\n\n${t("Surely, in the remembrance of Allah do hearts find comfort. — Qur’an 13:28","ألا بذكر الله تطمئن القلوب. — القرآن 13:28")}${eventText}${manageUrl?`\n\n${t("Manage alerts","إدارة التنبيهات")}: ${manageUrl}`:""}`;
 return{subject,html,text}
}
