import type { Env } from "./types";
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const text=(v:unknown,n=300)=>typeof v==="string"?v.trim().slice(0,n):"";
const makeCode=()=>"P"+crypto.randomUUID().replace(/-/g,"").slice(0,10).toUpperCase();
async function body(request:Request){const len=Number(request.headers.get("Content-Length")||0);if(len>32_768)throw new Error("Request too large");return await request.json().catch(()=>({})) as Record<string,unknown>}
async function studentByCode(env:Env,code:string){return env.DB.prepare("SELECT s.id,s.public_id,s.name,s.email,s.status,s.parent_code,s.current_surah,s.current_ayah,s.streak,s.stars,c.public_id class_public_id,c.name class_name,c.schedule_text,c.delivery_mode,t.name teacher_name FROM school_students s LEFT JOIN school_classes c ON c.id=s.class_id LEFT JOIN school_teachers t ON t.id=c.teacher_id WHERE s.parent_code=? AND s.status='active' LIMIT 1").bind(code.toUpperCase()).first<Record<string,unknown>>()}
export async function handlePublicSchool(request:Request,env:Env,url:URL){const p=url.pathname.replace(/^\/school\/?/,"").split("/");const route=p[0]||"config";
if(request.method==="GET"&&route==="config"){const {results}=await env.DB.prepare("SELECT setting_key,value_json FROM school_settings").all<Record<string,string>>();const settings:Record<string,unknown>={};for(const r of results){try{settings[r.setting_key]=JSON.parse(r.value_json)}catch{settings[r.setting_key]=r.value_json}}const {results:announcements}=await env.DB.prepare("SELECT public_id,title,message,audience,scheduled_at,created_at FROM school_announcements WHERE status='published' AND (scheduled_at IS NULL OR scheduled_at<=CURRENT_TIMESTAMP) ORDER BY id DESC LIMIT 20").all();return json({ok:true,settings,announcements})}
if(request.method==="GET"&&route==="class"&&p[1]){const code=decodeURIComponent(p[1]).toUpperCase();const c=await env.DB.prepare("SELECT c.public_id,c.name,c.invite_code,c.capacity,c.schedule_text,c.delivery_mode,t.name teacher_name,(SELECT COUNT(*) FROM school_students s WHERE s.class_id=c.id AND s.status='active') student_count FROM school_classes c LEFT JOIN school_teachers t ON t.id=c.teacher_id WHERE c.invite_code=? AND c.status='active' LIMIT 1").bind(code).first();return c?json({ok:true,class:c}):json({error:"Class code not found"},404)}
if(request.method==="POST"&&route==="join"){const b=await body(request),invite=text(b.inviteCode,30).toUpperCase(),name=text(b.name,140);if(!invite||!name)return json({error:"Class code and student name are required"},400);const c=await env.DB.prepare("SELECT id,public_id,name FROM school_classes WHERE invite_code=? AND status='active' LIMIT 1").bind(invite).first<{id:number;public_id:string;name:string}>();if(!c)return json({error:"Class code not found"},404);const count=await env.DB.prepare("SELECT COUNT(*) n FROM school_students WHERE class_id=? AND status='active'").bind(c.id).first<{n:number}>();const cap=await env.DB.prepare("SELECT capacity FROM school_classes WHERE id=?").bind(c.id).first<{capacity:number|null}>();if(cap?.capacity&&Number(count?.n||0)>=cap.capacity)return json({error:"This class is full"},409);const publicId=crypto.randomUUID(),parentCode=makeCode();await env.DB.prepare("INSERT INTO school_students(public_id,name,email,phone,class_id,parent_code,status,last_active_at) VALUES(?,?,?,?,?,?,'active',CURRENT_TIMESTAMP)").bind(publicId,name,text(b.email,254)||null,text(b.phone,60)||null,c.id,parentCode).run();return json({ok:true,student:{publicId,name,classPublicId:c.public_id,className:c.name,parentCode}},201)}
if(route==="student"&&p[1]){const code=decodeURIComponent(p[1]).toUpperCase(),student=await studentByCode(env,code);if(!student)return json({error:"Student access code not found"},404);const sid=Number(student.id);if(request.method==="GET"){const [assignments,memorization,attendance]=await Promise.all([env.DB.prepare("SELECT a.public_id,a.title,a.quran_reference,a.instructions,a.due_at,a.status,p.status progress_status,p.practice_count,p.ai_score,p.teacher_score,p.fluency_score,p.tajweed_score,p.teacher_feedback,p.last_practiced_at,p.submitted_at,p.reviewed_at FROM school_assignments a LEFT JOIN school_assignment_progress p ON p.assignment_id=a.id AND p.student_id=? WHERE a.status='published' AND (a.class_id=(SELECT class_id FROM school_students WHERE id=?)) AND (a.student_id IS NULL OR a.student_id=?) ORDER BY COALESCE(a.due_at,a.created_at) DESC").bind(sid,sid,sid).all(),env.DB.prepare("SELECT surah,ayah_start,ayah_end,activity_type,ai_score,teacher_score,fluency_score,tajweed_score,notes,created_at FROM school_memorization_log WHERE student_id=? ORDER BY id DESC LIMIT 100").bind(sid).all(),env.DB.prepare("SELECT attendance_date,status,note FROM school_attendance WHERE student_id=? ORDER BY attendance_date DESC LIMIT 100").bind(sid).all()]);delete student.id;delete student.parent_code;return json({ok:true,student,assignments:assignments.results,memorization:memorization.results,attendance:attendance.results})}
if(request.method==="POST"&&p[2]==="progress"&&p[3]){const assignmentId=decodeURIComponent(p[3]),b=await body(request);const a=await env.DB.prepare("SELECT id FROM school_assignments WHERE public_id=? AND status='published' LIMIT 1").bind(assignmentId).first<{id:number}>();if(!a)return json({error:"Assignment not found"},404);const existing=await env.DB.prepare("SELECT id,status,practice_count,ai_score FROM school_assignment_progress WHERE assignment_id=? AND student_id=?").bind(a.id,sid).first<{id:number;status:string;practice_count:number;ai_score:number|null}>();if(!existing){await env.DB.prepare("INSERT INTO school_assignment_progress(assignment_id,student_id,status,practice_count,ai_score,last_practiced_at,submitted_at,updated_at) VALUES(?,?,'in_progress',1,?,CURRENT_TIMESTAMP,CASE WHEN ?=1 THEN CURRENT_TIMESTAMP ELSE NULL END,CURRENT_TIMESTAMP)").bind(a.id,sid,Number(b.aiScore)||null,b.submit===true?1:0).run()}else{const next=b.submit===true?"submitted":existing.status==="assigned"?"in_progress":existing.status;await env.DB.prepare("UPDATE school_assignment_progress SET status=?,practice_count=practice_count+1,ai_score=MAX(COALESCE(ai_score,0),?),last_practiced_at=CURRENT_TIMESTAMP,submitted_at=CASE WHEN ?='submitted' THEN CURRENT_TIMESTAMP ELSE submitted_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(next,Number(b.aiScore)||0,next,existing.id).run()}await env.DB.prepare("UPDATE school_students SET streak=streak+1,stars=stars+?,last_active_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(Number(b.aiScore)>=90?3:1,sid).run();return json({ok:true})}}
return json({error:"School route not found"},404)}
